### ISSUE TITLE
all /grids/ views are broken

### ISSUE THREAD

**Issue by XavierLarrea** [djangopackages/djangopackages#1021]
**Describe the bug**
Clicking on any of the grid listings at the top, for example [deployment](https://djangopackages.org/grids/g/deployment/) generates an error

**To Reproduce**
1. Go to Home Page
2. Click on `Deployment` (or any package listed at the top)
3. See error

**Expected behavior**
Clicking on deployment will list out the packages that are deployment related

**Screenshots**

<img width="1366" alt="image" src="https://github.com/djangopackages/djangopackages/assets/9857779/b70399ca-4d19-4f61-b645-afaa70fc840e">

**Comment by RyanHope** [comment]
also getting this issue

**Comment by Duglaude59110** [comment]
me too 😢😭 but thx for your job

**Comment by Schroedingberg** [comment]
+1

**Comment by Kinbor1994** [comment]
also getting this issue
