### ISSUE TITLE
External link https://djangopackages.org/grids/g/linters/ broken

### ISSUE THREAD

**Issue by hamishwillee** [djangopackages/djangopackages#1022]
Just go to this list of Django aware linters: https://djangopackages.org/grids/g/linters/
This is the same URL you get to from search.

![image](https://github.com/djangopackages/djangopackages/assets/5368500/630c36a2-3785-4e0b-82e8-30194a34ff1b)

**Comment by ryancheley** [comment]
this is a duplicate of #1021

**Comment by jefftriplett** [comment]
Thank you for the report. Everything is fixed now. 

I'm afraid my bus factor + four days of flu + my youngest having a minor procedure (they are fine) was the perfect storm for me not being around to see this.

**Comment by hamishwillee** [comment]
Pleased to hear your youngest is well. No worries.
