### ISSUE TITLE
grid pages broken

### ISSUE THREAD

**Issue by dogukanakin** [djangopackages/djangopackages#1026]
from web

<img width="1678" alt="Ekran Resmi 2023-09-27 14 54 28" src="https://github.com/djangopackages/djangopackages/assets/101465660/6d1fa259-eaff-4fca-b449-c2a6a75b0bd8">

from phone

![Django Packages](https://github.com/djangopackages/djangopackages/assets/101465660/bf5ad4a1-e429-4151-8742-d2450f9407f5)

**Comment by the-ai-metiss** [comment]
Same issue here

**Comment by jefftriplett** [comment]
Thank you for the report. I'm afraid my bus factor + four days of flu + my youngest having a minor procedure (they are fine) was the perfect storm for me not being around to see this.
