### ISSUE TITLE
:pray: Thank You and Upcoming GitHub Permissions Update

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1058]
### Discussed in https://github.com/djangopackages/djangopackages/discussions/1054

<div type='discussions-op-text'>
<sup>Originally posted by **jefftriplett** November  4, 2023</sup>
</div>

Hello everyone 👋,

First and foremost, I'd like to express our deepest gratitude to everyone who has contributed to Django Packages over the years. Your dedication and effort have played a significant role in making this project what it is today. We sincerely appreciate all the time and energy you've invested here.

As part of our ongoing maintenance and to ensure the security of our repository, we're planning to update GitHub permissions at the end of the month on **Thursday, November 30, 2023**. This is a routine cleanup to manage access. Also, it might help some of our past contributors who no longer actively participate to stop receiving GitHub notifications.

## What does this mean for you?

- If you're still actively involved or wish to remain on the repository with the same level of access, please respond to this issue or contact us directly.
- If you've moved on to other projects and would prefer to have your permissions adjusted, you don't need to take any action; the update at the end of the month will take care of it.

This is purely an administrative action, and we hope it does not cause inconvenience. We're taking this step to ensure the best for our community and the security of our repository.

Thank you once again for being a part of our journey. We're looking forward to the continued growth and success of Django Packages with all your support!

Warm regards,
Jeff

**Comment by saadmk11** [comment]
Awesome, I would love to help maintain Django Packages. 😃

**Comment by jefftriplett** [comment]
⚠️  Reminder: *Thursday, November 30, 2023* is our deadline. I have heard from 4 or 5 people between this thread and the discussions thread.

**Comment by jefftriplett** [comment]
✅ This is done in the GitHub org settings. 
✅ This is done in the Django Packages Admin. 

I left @audreyfeldroy and @pydanny as members but happy to remove or bump your access back up.
