### ISSUE TITLE
Add documentation for rules logic

### ISSUE THREAD

**Issue by ryancheley** [djangopackages/djangopackages#1064]
**Is your feature request related to a problem? Please describe.**
When the updated rules are implemented there need to be docs to ensure the algorithm is accessible to users. This will also allow them to suggest / make improvements

**Describe the solution you'd like**
Add documentation for rules logic

**Comment by ryancheley** [comment]
@jefftriplett bd5c1bd shows a minimum implementation of the idea I mentioned yesterday for automated document generation based on the doc string of the Classes. It uses `cogapp` to populate the content of the markdown files

**Comment by jefftriplett** [comment]
@ryancheley nicely done. I like having `cogapp` around for documenting our `just` commands in our docs too. 👍  

Look PR-worthy to me. 

My only feedback is, can we put the bulk of the doc-templates code into its own file and call it from the rules files? That way we aren't bound by the rules docstrings if we want to add more text to the markdown files? Might be more flexible, but I'm reviewing before lunch and soccer ⚽

**Comment by ryancheley** [comment]
@jefftriplett I’m working on trying to get the doc-template to be in a better spot … my first attempts of putting it ‘where I think it goes’ was generating errors and I didn’t want to get **too** far into it before having someone else look at it 😁

I plan to work on making some updates over the holiday and hopefully the 🦃won’t put me into too much of a fugue state 🤣

**Comment by ryancheley** [comment]
I don't really like how the nav on the right side is being rendered

![image](https://github.com/djangopackages/djangopackages/assets/9857779/cdf95333-b231-4bfe-8ce0-1a9b4daf31fe)

I'm going to work on making changes to have it be a little less cluttered

**Comment by ryancheley** [comment]
with de295184c7bf54058407cd0538d017a59db64112 this is now completed
