### ISSUE TITLE
When logging in with the github authorisation it stops on a error screen

### ISSUE THREAD

**Issue by pescheck-bram** [djangopackages/djangopackages#1071]
**Describe the bug**
When logging in with the github authorisation it stops on a error screen

**To Reproduce**
1. Go to https://djangopackages.org/
2. Click on Login on the right top
3. Authorize with github

**Expected behavior**
When logging in i would expect it would log me in

**Screenshots**
![image](https://github.com/djangopackages/djangopackages/assets/78353155/41a07244-901f-4a63-89fd-c67dff5507ad)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: Version 119.0.6045.159 (Official Build) (64-bit)

**Comment by saadmk11** [comment]
Thank you for letting us know about this issue. :)

I tried to reproduce this issue but was unable reproduce it. My GitHub account is already connected to djangopackages.org. So, I was only able to try these two cases:

1. Directly Logging in through GitHub as GitHub authorization is already provided.
2. Revoking djangopackages.org authorization from GitHub using [Authorized OAuth Apps](https://github.com/settings/applications) settings and trying to login to djangopackages.org again which redirects me to the authorization page (Step 3) and after authorizing I am redirected to djangopackages.org without any error.

As I already have an account on djangopackages.org I was not able to test **first time login** case.

**Question:**
1. Is this the first time you are logging into djangopackages.org?

**Comment by pescheck-bram** [comment]
Yes it was the first time logging in.

**Comment by MAHMUD1223** [comment]
Hello. I am also getting the same error. I think there is a issue on first time login.

**Comment by jefftriplett** [comment]
Thank you for the report. I'll poke around and see if it's something with newer accounts.

**Comment by jefftriplett** [comment]
@pescheck-bram @MAHMUD1223 Thank you for reporting it. We had a stuck migration from the Python Social Auth (Django) package with three migrations behind. 

We got it unstuck and tested from GitHub and it created a new record. We hadn't had one since September 22nd, so I think we are good again. 

Apologies for the issue and thank you for bubbling it up to us.
