### ISSUE TITLE
Use Official PostgreSQL Docker Image for "postgres" Docker Service

### ISSUE THREAD

**Issue by saadmk11** [djangopackages/djangopackages#1077]
I'd like to remove the `postgres/Dockerfile` at some too since that feels like part of a different era and I don't see where that's useful anymore. 

_Originally posted by @jefftriplett in https://github.com/djangopackages/djangopackages/pull/1076#discussion_r1421759886_

**Comment by jefftriplett** [comment]
I'm 3 to 6 months of using the `pgautoupgrade/pgautoupgrade:latest` for a dozen+ projects and I'm a fan. The project/image is designed to make postgres upgrades painless and so far so good for me. 

I'm also happy to adopt one of the official images if that's preferred.

**Comment by saadmk11** [comment]
It's more of a convenience / safe choice than preferred. We can try out the one you suggested. :)

**Comment by jefftriplett** [comment]
I'm happy with either and I can also override it in compose override either way :) So whichever you prefer works for me.
