### ISSUE TITLE
Limit the size of data going into textfields to 500 characters

### ISSUE THREAD

**Issue by pydanny** [djangopackages/djangopackages#111]
If someone needs more than 500 then they are probably a spammer.

**Comment by vaibhav-jain** [comment]
Hi @pydanny,

Could you please let me know which fields needs to be fixed, I checked some but they have `max-length=100` set

**Comment by ryancheley** [comment]
It looks like there are 10 `TextFields` to review in the following Apps / Models:

## Grid

- Grid.description
- Feature.description
- Element.description

## Home Page

- PSA.body_text

## Package

- Category.description
- Package.repo_description
- Package.participants
- Package.commit_list

## SearchV2

- SearchV2.description
- SearchV2.participants

I don't think all of them need to have a limit of 500 characters, just those that are available from the front end. 

The next thing to do is:

- [ ] review the views for each model to see which fields are being called into the views
- [ ] review the templates to see what is being displayed on the front end

Once that is completed, a better assessment can be made (I think) about which fields should have the 500 character limit on them.

**Comment by ryancheley** [comment]
The `participation` fields appear to both be pulled in from GitHub so I don't think they would need to have the 500 character limit since there may be (and in many large project cases probably are) cases where a 500 character limit would truncate the list of contributors which wouldn't be correct.

**Comment by ryancheley** [comment]
Similarly, the `repo_description` and `commit_list` are also pulled from GitHub

**Comment by ryancheley** [comment]
Fields not available from the front end:

- Category.description
- SearchV2.description
- PSA.body_text

Fields that are available in front end:

- Feature.description
- Grid.description
- ElementForm
