### ISSUE TITLE
✨ Update Profile page options

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1115]
I noticed it's been a while since we updated our profile page. 

Both the detail page: https://djangopackages.org/profiles/jeff/
And then edit my profile page: https://djangopackages.org/profiles/edit/

- [x] Add GitLab as an option
- [x] Add Bitbucket as an option
- [x] We should normalize the spelling of GitHub (vs. Github)
- [x] Remove the Google Code `google_code_url`
- [x] Fix the `raw_id_fields` on the Profile model admin to avoid all ~15k users being rendered in a drop-down
- [x] Add social media or custom links? 
- [x] Create a changelog post about the new feature. 

We have room to expand our profile options if we want to add a description or any social websites.  

Also, see this thread for a potential follow-up feature to let people list their favorite packages: https://mastodon.social/@webology/112066712825122434

**Comment by ryancheley** [comment]
@jefftriplett for the favorite packages is the idea that IF a user has starred a project that is listed in Django Packages it would appear on their profile page, or would they have to actually add the favorite package from the list of one available from Django Packages? 

For the Social Media or Custom links, we could take a page from Mastodon and have an `extra fields` section.

<img width="556" alt="image" src="https://github.com/djangopackages/djangopackages/assets/9857779/7d560af3-3c90-4a10-b3e7-5a67d153521d">

**Comment by jefftriplett** [comment]
@ryancheley I like that a lot. I'm not sure if we are asking for more spam, but we can mitigate some of that by using `rel="nofollow"`.

**Comment by ryancheley** [comment]
@jefftriplett I have some ideas on how to implement this and will take a swing at making it work 😄

**Comment by jefftriplett** [comment]
@ryancheley yes plz. Ping me if you need a body to throw ideas at. I have no real implementation plan in mind outside of, Mastodon is a good place to get inspiration from.

**Comment by jefftriplett** [comment]
@ryancheley tests run clean to me. I run `pytest --create-db` when there are schema changes. 

How do you feel about making them their own table and adding them as an inline in the form? Then we could set it maybe show max of 4 (with room to expand if we wanted)?

I was curious how Mastodon does, and as best as I could tell, they use a JSON field. https://github.com/mastodon/mastodon/blob/main/db/schema.rb#L186 

Not sure I'd want to do that but it's interesting.

**Comment by ryancheley** [comment]
@jefftriplett the extra flag did it for me thanks! I did initially have it set as it's own table but changed direction based on what the Mastodon interface looked like. I'm going to go back on that route and see how it goes

**Comment by ryancheley** [comment]
There is a failing test `profiles/tests/test_views.py::TestProfile::test_edit` that needs to be addressed

**Comment by jefftriplett** [comment]
@ryancheley back from break and it looks like you figured this out. Let me know if you need me to help with anything.

**Comment by ryancheley** [comment]
@jefftriplett I think at this point just a review on the PR (#1125) I just made 😄

**Comment by jefftriplett** [comment]
I don't think it has to be too formal. Some copy with maybe an option image, which means we'll have to figure out how to add an image. (feel free to drop it here for now) 

Inspiration: https://buttondown.email/changelog

**Comment by ryancheley** [comment]
@jefftriplett here's my initial draft. Not sure if this is too short, or just right 🤷 

Profiles now include Social Links!

- Add up to 4 links to your Social Media pages like Mastodon, LinkedIn, Personal Blog, YouTube, etc

![image](https://github.com/djangopackages/djangopackages/assets/9857779/d0f7201c-3900-4e18-b2f1-63c317a6d485)

**Comment by jefftriplett** [comment]
@ryancheley checking this out.

**Comment by jefftriplett** [comment]
@ryancheley good work. I made a post but I'll have to backfill the image/come up with a better solution for it. GitHub doesn't keep it around for very long, so I switched to a Mastodon post until I can get better solution for images: https://mastodon.social/@webology/112339657610497765
