### ISSUE TITLE
Move GOTW & DOPTW to grid/package models respectively

### ISSUE THREAD

**Issue by pydanny** [djangopackages/djangopackages#112]
- Nuke the old GOTW and DOPTW models
- Add featured/featured_description fields to Grid/Package models
- generate schemamigrations
- Change the home page view to reflect the data changes.

**Comment by ryancheley** [comment]
After talking with @jefftriplett the approach we'll be taking is to reimplement the GOTW and DOPTW first and then if necessary refactor the location of the models
