### ISSUE TITLE
🐛 Google charts seems to be no longer available, commits chart is now a broken image

### ISSUE THREAD

**Issue by corentinbettiol** [djangopackages/djangopackages#1128]
**Describe the bug**

The charts on packages detail pages are no longer available:

![image](https://github.com/djangopackages/djangopackages/assets/45763865/6f9f9aa1-a934-49c4-a62b-fe58b132c190)

And https://chart.googleapis.com/ return a 404.

Their [help page](https://developers.google.com/chart/image) indicate that the service should have been discontinued since 2019:

![image](https://github.com/djangopackages/djangopackages/assets/45763865/e8a78f3d-0003-4a9f-ab60-bd6e5ff72d21)

**To Reproduce**
1. Go to any package detail page.
2. See missing commits chart

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Comment by saadmk11** [comment]
Thank you for reporting this issue. 💯

We have couple of options here:

1. (Preferable) Try to use a similar alternative to Google Chart Image API. For example: Quick Chart is a similar service to Google Chart Image API (https://quickchart.io/), we can try it out.

2. Build a custom solution possibly using Chart.js.

3. Remove this feature for now.
