### ISSUE TITLE
🚜 Convert sitemaps from a Django templates 

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1146]
I noticed tonight that our sitemap.xml is a home `rolled` view + template. We should port this over to `django.contrib.sitemaps` and ideally use a [sitemap index](https://docs.djangoproject.com/en/5.0/ref/contrib/sitemaps/#creating-a-sitemap-index) to help cut down on the overall rendering time. 

- [ ] Static pages
- [ ] Packages 
- [ ] Grids
- [ ] Blog

See template: https://github.com/djangopackages/djangopackages/blob/main/templates/sitemap.xml#L1-L24

**Comment by jefftriplett** [comment]
@saadmk11 great work. Here's it working in production: https://djangopackages.org/sitemap.xml

**Comment by saadmk11** [comment]
> @saadmk11 great work. Here's it working in production: https://djangopackages.org/sitemap.xml 

Awesome 🍻

**Comment by jefftriplett** [comment]
@saadmk11 I added it the changelog. 

https://djangopackages.org/changelog/2024-04-28-revamping-sitemap-generation-on-django-packages/
