### ISSUE TITLE
Login fails at the moment

### ISSUE THREAD

**Issue by danirus** [djangopackages/djangopackages#1149]
**Describe the bug**
Seems like there is an issue when trying to login in djangopackages.com.

**To Reproduce**
1. Go to [https://djangopackages.org/](https://djangopackages.org/)
2. Click on 'login'
3. See error

**Screenshots**
I attach a screenshot.

<img width="1221" alt="Screenshot 2024-05-02 at 09 13 52" src="https://github.com/djangopackages/djangopackages/assets/157103/b40499bb-e8e7-4690-af3f-ed60ec6b5626">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1
 - Browser chrome
 - Version 124.0.6367.92 (Official Build) (arm64)

Thanks for developing and maintaining djangopackages! :-)

**Comment by saadmk11** [comment]
I can confirm this issue, I am also unable to login using GitHub.

https://djangopackages.org/auth/complete/github/?code=some-code&state=some-state

return 500 error.

We should probably check Sentry for any error related to this.

**Comment by jefftriplett** [comment]
This might be related to https://github.com/djangopackages/djangopackages/pull/1145 

I'm just seeing this and looking now.

**Comment by jefftriplett** [comment]
This appears to be fixed. I tried logging out and I couldn't log back in. I downgraded social-auth-app-django and pinned it and everything seems to work again. 

It might be related: https://github.com/python-social-auth/social-app-django/issues/568

I'll leave this open until we get a few other confirmations. 

Thank you for the report!

**Comment by jefftriplett** [comment]
Side-note: This was in Sentry but only generated 61 errors. I'll see what the Team options are.

**Comment by saadmk11** [comment]
@jefftriplett Thanks for looking into the issue 💯. It is also fixed for me. 😃

**Comment by danirus** [comment]
Thanks! 🙂
