### ISSUE TITLE
:pencil: Add documentation_url to the Add/Edit Package form

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1162]
Add the `documentation_url` field to the Add/Edit Package form. 

This is a quick win and should only require adding the field name to the `PackageForm` in `package/forms.py.` 

- https://djangopackages.org/packages/add/
- https://djangopackages.org/packages/django-cool-urls/edit/

**Comment by jefftriplett** [comment]
TODO: Add a ticket/research how to pull the documentation link from PyPI's metadata if `Package.documentation_url is None` and the value exists.

**Comment by FarhanAliRaza** [comment]
![image](https://github.com/djangopackages/djangopackages/assets/62690310/a1a770d7-2f2d-441d-8440-b8ef63ecde63)
Many projects have Documentation URLs in project URLs. But many do not have that they only mention it in description. 
The simple way is to look for the ```Documentation``` key in project_urls if exists update the model.

**Comment by FarhanAliRaza** [comment]
Should it be implemented in the ```fetch_pypi_data``` function of Package model?

**Comment by FarhanAliRaza** [comment]
From the description, it can also extracted by simply searching for ```[Documentation]``` in word
