### ISSUE TITLE
:bug: Fix docs in Code Spaces

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1166]
> I tried to look at it in code spaces, but wasn't able to figure out how to run the docs there. The main project runs just fine. Maybe this is something worth documenting? That is, how to run the documentation in Code Spaces

_Originally posted by @ryancheley in https://github.com/djangopackages/djangopackages/pull/1165#pullrequestreview-2096507481_

**Comment by FarhanAliRaza** [comment]
When I open the codespace container by default it does not have git installed.  It does run the web application. So my understanding is it runing it from the already present docker file.
But without git i can not create new branch to make the changes.

**Comment by jefftriplett** [comment]
A few of us looked at this on Friday and noticed the same thing. I think we need to take a few hours and dive into devcontainers to see if there's a better fix either through VS Code editor or if we need to add git to the container directly.
