### ISSUE TITLE
✨ Favorite Packages: Write-up

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1170]
This feature has a few layers, including giving people the ability to star or favorite projects. These may be optionally displayed on your profile. 

WIP: This can be turned into small issues as we finish up the details. 

----

# Favorite Packages

## Description

We need to add the functionality for users to favorite third-party packages on Django Packages. Additionally, we want to track how many users have favorited each package without hitting the database too hard. This will involve changes to our models and additional logic to manage favorite counts efficiently.

## Acceptance Criteria

- Users can favorite and unfavorite packages.
- The `favorite_count` for each package is updated correctly without significant performance impact.
- The admin interface displays and allows the efficient management of favorites and packages.

#### ~~`Package` Model (existing model)~~ #1203 (**done**)

Add a new field `favorite_count: int = 0` to track the number of users who have favorited the package.

#### ~~`Favorite` Model (new)~~ #1201 (**done**)

- This table should connect a `User` to the `Package` model along with a `favorited_at: date = timezone.now()` field.
- Override the save method to increment the `favorite_count` of the associated Package when a new favorite is created.
- Override the delete method to decrement the `favorite_count` when a favorite is removed.
- The Favorite model should be registered in `admin.py` and include `raw_id_fields` for both user and the package models. 

#### `User` model (existing model) #1202

- Add a `share_favorites: bool = False` field, which we will use to determine if a User wants to share their favorite packages publicly or not. 

### View Updates

1. Favorite Package View:
   - Create a new view to handle favoriting a package.
   - This view should:
     - Accept a POST request with the package ID.
     - Check if the user is authenticated.
     - Create a new Favorite object linking the user to the package.
     - Redirect back to the package detail page. (optionally, see note about htmx)
   - Add appropriate URL routing for this view.

2. Remove Favorite View:
   - Create a new view to handle unfavoriting a package.
   - This view should:
     - Accept a POST request with the package ID.
     - Check if the user is authenticated.
     - Find and delete the Favorite object for the user and package.
     - Redirect back to the package detail page. (optionally, see note about htmx)
   - Add appropriate URL routing for this view.

3. Modify User Profile View:
   - Update the existing user profile view to include favorite packages.
   - This modification should:
     - Retrieve the user's favorite packages if `share_favorites` is True.
     - Add the list of favorite packages to the context data.
   - Update the user profile template to display the favorite packages.

Additional Considerations:
- Implement proper authentication and authorization checks in all views.
- Add appropriate error handling and user feedback (e.g., messages framework).
- Update the package detail template to include a form for favoriting/unfavoriting.
- Ensure all views are tested thoroughly.
- Consider adding a confirmation step before unfavoriting a package.
- Optionally use htmx to favorite/remove

This approach will provide a more traditional web experience, with page reloads after each action.

**Comment by jefftriplett** [comment]
cc @vcruces @lipemorais @FarhanAliRaza @ontowhee for feedback. I'm drafting the view portion. 

Based on these proposed changes, the goal is to create several small tickets. We'll land models first and then view + templates + test next.

**Comment by FarhanAliRaza** [comment]
Should not the `favorite_count` field be registered in Package Admin?

**Comment by jefftriplett** [comment]
> Should not the `favorite_count` field be registered in Package Admin?

@FarhanAliRaza Nice catch. Added to a new issue https://github.com/djangopackages/djangopackages/issues/1210
