### ISSUE TITLE
:pencil: Fix contributing docs

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1171]
Our contributing docs have drifted from our install docs, and we even call out a develop branch that we don't use. 

- https://docs.djangopackages.org/en/latest/contributing/
- See https://docs.djangopackages.org/en/latest/contributing/#pull-upstream-changes-into-your-fork-regularly

**Comment by FarhanAliRaza** [comment]
![image](https://github.com/djangopackages/djangopackages/assets/62690310/03bcb981-65bf-473d-a8ac-fa2d549e3e55)
How to handle this part ?

```
git pull git://github.com/<submitter-github-name/djangopackages.git develop
```
changes to 


```
git pull git://github.com/<submitter-github-name/djangopackages.git main
```
and these command
```
git checkout develop
git merge <branch-name>
git push origin develop
```

to 
```
git checkout main
git merge <branch-name>
git push origin main
```
is it correct?

**Comment by jefftriplett** [comment]
@FarhanAliRaza good work. Before I close this, I wanted to double-check that you didn't still have questions, since it looked like you'd answered them in your pull request.

**Comment by jefftriplett** [comment]
Awesome. We can iterate on them if we aren't there yet.
