### ISSUE TITLE
✨ Add an opensearch description file

### ISSUE THREAD

**Issue by bmispelon** [djangopackages/djangopackages#1174]
It would be nice to have a `<link rel="search" ...>` pointing to [an opensearch description file](https://developer.mozilla.org/en-US/docs/Web/OpenSearch).

This lets you add the search engine to your browser directly (on my browser a menu item shows up when I right click on the URL bar on a site that supports it).

For reference/inspiration, here's how it looks like for docs.djangoproject.com: https://github.com/django/djangoproject.com/blob/main/docs/templates/docs/search_description.xml

**Comment by FarhanAliRaza** [comment]
Do we need it only in docs or for all site?

**Comment by FarhanAliRaza** [comment]
in Django https://github.com/django/djangoproject.com/blob/7ab136878579cdd4c3fe2a1b879f6bbe48979301/docs/views.py#L224
this handles the actual search for OpenSearch. So, do we need to implement our custom view for search? Another method would be to use a search engine like DuckDuck to go and pass the query(I think).

**Comment by FarhanAliRaza** [comment]
@bmispelon, the Django docs implemented this feature, but after a lot of searching, I still can't use it on my Chrome and Firefox browsers. I don't see any special search box or menu item when I click on the URL box. Can you please send a screenshot showing how to use this feature on Chrome or Firefox? .. It will be a great help. That way, I can test what I am doing. @jefftriplett

**Comment by jefftriplett** [comment]
> Do we need it only in docs or for the main site?

We can skip the docs. It would be useful to find packages and grids on the main website. 

> So, do we need to implement our custom view for search? Another method would be to use a search engine like DuckDuck to go and pass the query(I think).

Yes, we want two views. 

1. The first view should return the OpenSearch Xml template. We can copy this file https://developer.mozilla.org/en-US/docs/Web/OpenSearch#opensearch_description_file 

  We can swap out `https://example.com` paths for our project and then update the `moz:SearchForm` url to our next view.

  When I view source on it:
  
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>Django 5.0 documentation</ShortName>
  <Description>Search Django 5.0 documentation</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <OutputEncoding>UTF-8</OutputEncoding>
  <Image width="16" height="16" type="image/x-icon">https://static.djangoproject.com/img/favicon.6dbf28c0650e.ico</Image>
  <Image width="32" height="32" type="image/x-icon">https://static.djangoproject.com/img/favicon.6dbf28c0650e.ico</Image>
  <Query role="example" searchTerms="testing" />
  <Developer>Django team</Developer>
  <SyndicationRight>open</SyndicationRight>
  <AdultContent>false</AdultContent>
  <Language>en</Language>
  <Url type="application/x-suggestions+json" rel="suggestions" template="https://docs.djangoproject.com/en/5.0/search/suggestions/?q={searchTerms}"/>
  <Url type="text/html" rel="results" method="get" template="https://docs.djangoproject.com/en/5.0/search/?q={searchTerms}"/>
  <Url type="application/opensearchdescription+xml" rel="self" template="https://docs.djangoproject.com/en/5.0/search/description/"/>
</OpenSearchDescription>
```



2. We need a search view that returns a `JsonReponse`. This is where we can follow what Django is doing from this https://github.com/django/djangoproject.com/blob/7ab136878579cdd4c3fe2a1b879f6bbe48979301/docs/views.py#L224-L273 

> Can you please send a screenshot showing how to use this feature on Chrome or Firefox?

I'm using Vivaldi, which integrates this as a search/auto-complete option. I can try to pull it via Chrome tomorrow.

**Comment by bmispelon** [comment]
On my firefox, the option appears when I right-click the URL bar:

![djangoproject_opensearch](https://github.com/user-attachments/assets/bb20a2cb-71de-43e9-8a90-1631046adb6b)

**Comment by jefftriplett** [comment]
Hey @bmispelon, this is deployed now. Would you mind giving it a try in production and let us know if you see something off? 

AFAICT, it's working... 
<img width="1242" alt="Xnapper-2024-07-17-22 24 20" src="https://github.com/user-attachments/assets/3bc78a17-d48d-41e2-a3dc-e1d35e5bc49a">

**Comment by bmispelon** [comment]
I was able to add the search engine, and searching with it appears to work.

Good job @FarhanAliRaza (and everyone involved) 🚀
