### ISSUE TITLE
:tractor: Refactor `favorite.save()` and `favorite.delete()`

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1207]
This is a low priority, but let's refactor `favorite.save()` and `favorite.delete()` to use an [`F() expression`](https://docs.djangoproject.com/en/5.0/ref/models/expressions/#f-expressions). 

Using an `F()` expression scales better when adding/subtracting a value. 

These are the two places in the code where we need to modify it: 

- https://github.com/djangopackages/djangopackages/blob/37156209d798724bcf965ea9fc3efbc1291ebf08/favorites/models.py#L15
- https://github.com/djangopackages/djangopackages/blob/37156209d798724bcf965ea9fc3efbc1291ebf08/favorites/models.py#L19

## How big of a deal is this change? 

It's not. It's more of a best practice change than one I'm really worried about multiple people liking the same package at the same time. 

We also can always re-count the number of Favorite records that a package has to adjust them if we ever think they are off.

**Comment by jefftriplett** [comment]
cc @FarhanAliRaza is this one you'd want to pick up?

**Comment by FarhanAliRaza** [comment]
Yes I will do that
