### ISSUE TITLE
:sparkles: Favorite Packages: Favorite Package view

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1212]
Create a new view to handle favoriting a package.

## Details: 
 - This view should:
     - Accept a POST request with the package ID.
     - Check if the user is authenticated.
     - Create a new Favorite object linking the user to the package.
     - Redirect back to the package detail page. (optionally, see note about htmx)
 - Add appropriate URL routing for this view.

## Additional Considerations (may apply to all views):
- Implement proper authentication check in all views.
- Add appropriate error handling and user feedback (e.g., messages framework).
- Update the package detail template to include a form for favoriting/unfavoriting.
- Ensure all views are tested thoroughly.
- Consider adding a confirmation step before unfavoriting a package.
- Consider using htmx to favorite/remove a favorite. 

---- 

See #1170 for more details.

**Comment by FarhanAliRaza** [comment]
![Screenshot from 2024-07-22 21-44-21](https://github.com/user-attachments/assets/e79a44bb-1584-415e-a092-a6ecab76dc4a)
How a favorite form should look like something like this? @jefftriplett
