### ISSUE TITLE
🔘  Create a favorite package feature flag

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1227]
Let's add a [Waffle Feature flag](https://waffle.readthedocs.io/en/stable/types/flag.html) around the feature flag on the package details page so we can turn them on privately for testing. 

Django Waffle is already installed so we just need to configure it on the `templates/package/package.html`.

**Comment by FarhanAliRaza** [comment]
have we created a flag for this feature ? What is the name of the flag?
