### ISSUE TITLE
:bug: Double check tests run cleanly

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1235]
I think the todo here is to update the docs to call out the `--create-db` flag or we might want to update our pytest config to be a little slower by default to avoid the need for it.

**Comment by jefftriplett** [comment]
From my home home Mac (M2 model), I'm seeing: `186 passed, 4 xfailed in 17.49s`

**Comment by vcruces** [comment]
Yes, with the `--create-db` flag all tests passed on my machine. Thanks Jeff!

**Comment by jefftriplett** [comment]
@vcruces fixed in #1270 so the default test run will just work now. Thank you for reporitng it.
