### ISSUE TITLE
:arrow_up: Upgrade to Django 5.1

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1246]
[Django 5.1](https://www.djangoproject.com/weblog/2024/aug/07/django-51-released/) is out. 

And while we are in no rush to upgrade, we should see if anything breaks. In theory, we could target 5.1.1 or 5.1.2 unless everything just works. 

See also my guide on when I feel it's safe to upgrade: https://micro.webology.dev/2024/02/01/choosing-the-right.html 

Blocked on https://github.com/etianen/django-reversion/issues/974

**Comment by saadmk11** [comment]
Fix for https://github.com/etianen/django-reversion/issues/974 has been released on version `5.1.0` (https://github.com/etianen/django-reversion/releases/tag/v5.1.0)

**Comment by saadmk11** [comment]
I checked out the release notes, seems like we don't need to make many changes to the code-base for this upgrade. I am interested to try out [PostgreSQL Connection Pools](https://docs.djangoproject.com/en/5.1/releases/5.1/#postgresql-connection-pools) after we complete the upgrade. :)
