### ISSUE TITLE
Safari login broken in dev environment

### ISSUE THREAD

**Issue by giaume** [djangopackages/djangopackages#1276]
**Describe the bug**

Login is broken with Safari, works with Chrome and Firefox.

**To Reproduce**

- Install a fresh dev environment following README.md instructions
- Create a superuser
- Try to login from http://localhost:8000/admin/ using Safari
- It goes back to login/password without any error.

**Expected behavior**

Get logged in.

**Additional context**

Sniffing network shows the server response to POST has:

```
Set-Cookie:  sessionid=XXX; expires=Thu, 10 Oct 2024 18:59:02 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax; Secure
```

It looks like Safari is then not passing this cookie because it's http (not https) and cookie is marked as `Secure`,
therefore we get the login page again and no error message at all.

**Solution**

Change in `settings/docker.py`:

```
SESSION_COOKIE_SECURE = False
```

**Comment by giaume** [comment]
Same behavior (can't log in) using Firefox or Chrome with http://0.0.0.0:8000/admin/

But for both Firefox and Chrome, it works with http://localhost/admin/ or http://127.0.0.1/admin/, they must have some hard-coded exceptions to ignore the `Secure` cookie attribute for `localhost` and for `127.0.0.1`, which Safari does not have.

**Comment by jefftriplett** [comment]
This should now be taken care of in #1280. 

Thank you for reporting it and doing all of the work to track down a fix.
