### ISSUE TITLE
There is no management command for searchv3_build but it's referenced the docs

### ISSUE THREAD

**Issue by ryancheley** [djangopackages/djangopackages#1278]
**Describe the bug**

In the `install.md` docs there is a reference to the [version 3 API management command](https://github.com/djangopackages/djangopackages/blob/main/docs/docs/install.md#rebuild-search-indexes) to rebuild indexes but when it's run it generates the following error

```
[+] Creating 2/0
 ✔ Container djangopackages-redis-1     Running                                                                                                                              0.0s 
 ✔ Container djangopackages-postgres-1  Running                                                                                                                              0.0s 
Postgres is up - continuing...
Unknown command: 'searchv3_build'. Did you mean searchv2_build?
Type 'manage.py help' for usage.
```

**To Reproduce**
1. From the command line run the command `docker compose run --rm django python -m manage searchv3_build`
2. Notice the error `Unknown command: 'searchv3_build'. Did you mean searchv2_build?`

**Expected behavior**
When running the command it should return output similar to `searchv2_build`

```
[+] Creating 2/0
 ✔ Container djangopackages-redis-1     Running                                                                                                                              0.0s 
 ✔ Container djangopackages-postgres-1  Running                                                                                                                              0.0s 
Postgres is up - continuing...
Commencing search result building now Thu, 26 Sep 2024 19:55:16 +0000
Finished at Thu, 26 Sep 2024 19:55:17 +0000
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: NA
 - Version: NA

**Additional context**
I discovered this while working on #1189

**Comment by jefftriplett** [comment]
🤦 

![Image](https://github.com/user-attachments/assets/fcd23bb9-61d4-4b40-b06a-f9c8a3f7aac9)
