### ISSUE TITLE
💅  Add djade

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1282]
Since @ryancheley brought it up, [djade](https://github.com/adamchainz/djade) feels worth exploring. 

https://mastodon.social/@ryancheley/113256579926595513

**Comment by saadmk11** [comment]
Interesting, I haven't heard of this project before. I added a PR (https://github.com/djangopackages/djangopackages/pull/1283) to try this out. :)

**Comment by jefftriplett** [comment]
:rocket: This is deployed now.
