### ISSUE TITLE
API v4 Search and Package Detail Endpoint Integration Limitations

### ISSUE THREAD

**Issue by saadmk11** [djangopackages/djangopackages#1292]
This weekend, I attempted to build an integration using the Search and Package Detail APIs (API v4).
However, I encountered a limitation: the Package Detail API requires `Package.id` to retrieve a specific package, while the Search API doesn't return `Package.id` (or, `Grid.id` for Grids).

Upon further investigation of the code, I discovered that the Search API utilizes the `SearchV2` Model for returning search results. This model, does not store the `ID` of objects like `Package.id` and `Grid.id`. While this approach is suitable for front-end functionality where `slugs` are used for fetching object details, it presents a challenge for API integrations requiring object IDs.

To fix this issue we can either:

- Add a new field (`item_id`) to `SearchV2` model that stores the `ID` of the object. (We already store the type of the object inside `item_type` field)

Or,

- We can update the Package and Grid Detail API so that they accept both `ID` and `Slug` for DB lookup’s. (It will probably be a bit **hacky** as DRF does not support this by default). For Example:

```diff
diff --git a/apiv4/viewsets.py b/apiv4/viewsets.py
index 00ad260a..81445b67 100644
--- a/apiv4/viewsets.py
+++ b/apiv4/viewsets.py
@@ -37,6 +37,12 @@ class PackageViewSet(viewsets.ReadOnlyModelViewSet):
     queryset = Package.objects.all().order_by("-id")
     serializer_class = PackageSerializer
     paginate_by = 20
+    lookup_url_kwarg = "pk_or_slug"
+
+    @property
+    def lookup_field(self):
+        obj_ident = self.kwargs[self.lookup_url_kwarg]
+        return "pk" if obj_ident.isdigit() else "slug"
```

**Comment by jefftriplett** [comment]
@saadmk11 either solution is fine, but I lean towards the second because your example doesn't look that bad to me. 

There shouldn't be a huge number of people using our APIs so we can deal with any fallback that happens (if there even is any). I think the Wagtail Packages page (https://wagtail.org/packages/) might be the only group I have heard from after an API change.

**Comment by saadmk11** [comment]
> [@saadmk11](https://github.com/saadmk11) either solution is fine, but I lean towards the second because your example doesn't look that bad to me.
> 
> There shouldn't be a huge number of people using our APIs so we can deal with any fallback that happens (if there even is any). I think the Wagtail Packages page (https://wagtail.org/packages/) might be the only group I have heard from after an API change.

This approach should not modify any existing behaviour , it will just add onto it.
- https://github.com/djangopackages/djangopackages/pull/1296
