### ISSUE TITLE
Funkybob sees not what he contributes to

### ISSUE THREAD

**Issue by pydanny** [djangopackages/djangopackages#161]
http://djangopackages.herokuapp.com/profiles/funkybob

It's a problem with profiles.models.Profile.my_packages. I'll open a ticket.

**Comment by jayfk** [comment]
That's probably a casing issue. At some point in time the account was created as `FunkyBob` but is now called `funkybob`.

**Comment by funkybob** [comment]
Yes, I believe that was established some time ago... but clearly not logged on this ticket.

**Comment by vaibhav-jain** [comment]
Closing this as it is fixed see https://github.com/djangopackages/djangopackages/issues/144 for more info.
