### ISSUE TITLE
searchv2_build needs to send email, not write to logs

### ISSUE THREAD

**Issue by pydanny** [djangopackages/djangopackages#164]
- Runs once per day
- Old way saved to log file
- New way needs to send out email
- searchv2.management.commands.searchv2_build

**Comment by jayfk** [comment]
This now logs to stdout captured by systemd. Thanks to https://github.com/djangopackages/djangopackages/commit/061efd927f72cd70dda890fcec4eec4df3757f7e there's now also a healthcheck in place.
