### ISSUE TITLE
Remove package from a grid

### ISSUE THREAD

**Issue by vdboor** [djangopackages/djangopackages#182]
Hi,

I accidentally added a package to the wrong grid (http://www.djangopackages.com/packages/p/django-like/). Is there a way I can undo this? I didn't find such feature.

**Comment by renkse** [comment]
Hi @pydanny! Could you help me too? I accidentally added [django-nav-menu](https://www.djangopackages.com/packages/p/django-nav-menu/) to the [Contact Import and Management](https://www.djangopackages.com/grids/g/contact/) grid. Could you remove the last one please? Thanks in advance.

**Comment by adi-** [comment]
Hi, also my package `django-markdownx` (https://www.djangopackages.com/packages/p/django-markdownx/) has somehow landed twice in `WYSIWYG Editors` Grid. Could you fix that?

**Comment by vdboor** [comment]
@renkse, @adi- I've removed both packages from the grids for you.

@pydanny It looks like the package is removed from the grid (given the detail page), but the grid still shows it (guess that's cached).

**Comment by renkse** [comment]
@vdboor Thanks for help!

**Comment by pydanny** [comment]
Thanks for taking care of that @vdboor. Yes, it's cached and will take a bit to clean itself up. :smile:

**Comment by michaelkuty** [comment]
Hi, please can you delete one package from grid for me ?

django-leonardo from https://www.djangopackages.com/grids/g/mezzanine/

Thanks !

**Comment by vdboor** [comment]
@michaelkuty done. The page still shows results as changes don't clear the grid cache.
