### ISSUE TITLE
When changing PyPI slug, need to clear previous package info

### ISSUE THREAD

**Issue by audreyr** [djangopackages/djangopackages#277]
For example, with this package: https://www.djangopackages.com/packages/p/shpaml/

I changed the PyPI slug from `shpaml` to `django-shpaml`, to reflect what it says in the readme at https://github.com/Rootbuzz/shpaml.

Then I clicked the [Fetch latest data] button.

The correct package info is there (1.2.0    BSD 02/02/2014  Unknown). However, the previous incorrect package info (1.00b   Freely Distributable    04/10/2011  Beta) is also still present and was not deleted.

**Comment by vaibhav-jain** [comment]
Hi @audreyr,

I think it is working now as expected could you please confirm.
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/4224414/68801008-2cc6df00-0681-11ea-9ef1-887443fe088a.png">

**Comment by vaibhav-jain** [comment]
Closing it now, Please feel free to open it if needed :)
