### ISSUE TITLE
FAQ: How to request for new lines in a grid

### ISSUE THREAD

**Issue by guettli** [djangopackages/djangopackages#283]
Please add a new question and its answer to:

https://www.djangopackages.com/faq/

"How to request for new lines a comparison grid?"

Thank you.

**Comment by jayfk** [comment]
> My patch was accepted! so we should be able to close this ticket too.

Almost three years. Better now than never :)

**Comment by guettli** [comment]
@AnneTheAgile  thank you for your patch
