### ISSUE TITLE
PyPI Alpha/beta versions not sorted properly

### ISSUE THREAD

**Issue by vdboor** [djangopackages/djangopackages#288]
I noticed versions are not sorted properly. For example, my django-parler package:
https://www.djangopackages.com/packages/p/django-parler/

It lists 1.0b3 before the 1.0 final release. In the grid, it will also show 1.0b3 as latest release.

p.s. what happened to opencomparison? Couldn't find it on GitHub anymore.

**Comment by jayfk** [comment]
I've removed beta/alpha/rc packages from djangopackages.org.
