### ISSUE TITLE
Enhancement: Link to a "skeleton" or "template" for INSTALLED_APPS authors

### ISSUE THREAD

**Issue by brycenesbitt** [djangopackages/djangopackages#292]
I'd love to see a link on djangopacakages to
a good tutorial on package writing, or better yet
a "skeleton" or "template" for an INSTALLED_APPS package.

**Comment by jayfk** [comment]
I think there are better resources for something like this. There's a vast amount of blog posts, tutorials, books and video content available on how to do that.
