### ISSUE TITLE
Allow removal of specific versions

### ISSUE THREAD

**Issue by yakky** [djangopackages/djangopackages#303]
This is somewhat related to #288
Some versions are meant to be temporary (say betas, alphas) and it may be useful to remove them from the history list after they have been removed from PyPi
If not automatically synced with PyPi there should be a way to manually remove them from the versions list

**Comment by pydanny** [comment]
I don't believe versions can be removed from PyPi

**Comment by yakky** [comment]
They can
![pypi_remove](https://cloud.githubusercontent.com/assets/714711/10475978/c41b065e-7249-11e5-8d54-101e68f378dc.jpg)

**Comment by pydanny** [comment]
OK. I'll do it! :)

**Comment by yakky** [comment]
If you can provide some guidance on how to do this, I'll happily help

**Comment by jayfk** [comment]
This will go away once PyPi migrates to the new warehouse implementation.

**Comment by yakky** [comment]
Thanks @jayfk
