### ISSUE TITLE
Have tests authenticate into Github locally to avoid low rate limit failures

### ISSUE THREAD

**Issue by audreyr** [djangopackages/djangopackages#315]
This is set up already for Travis CI.

May just be a matter of documenting what value to set the `GITHUB_TOKEN` env var to.

**Comment by audreyr** [comment]
Actually, we need to fix this on Travis too. See https://travis-ci.org/pydanny/djangopackages/builds/50424855

**Comment by jayfk** [comment]
The basic rate limiting in `package_updater` seems to work 👍
