### ISSUE TITLE
"Add package" page locks up if you input a URL and then clear it out.

### ISSUE THREAD

**Issue by kezabelle** [djangopackages/djangopackages#322]
angular digest loop fun, perhaps?
## Steps to reproduce
- Navigate to https://www.djangopackages.com/packages/add/ as an authenticated user.
- Paste https://github.com/opencomparison/opencomparison into the _Repo URL_ field.
- Observe the other fields are updated based on that value.
- Ctrl-A the existing Repo URL value to select all. 
- Press delete, to clear the selection.
- Observe that the page stops responding to events (click, focus, etc)
- Close the window and come here :)

Experienced on Chrome 44.0.2403.52 beta (64-bit) on OSX 10.8.4

**Comment by hebertjulio** [comment]
Issue solved, waiting closing. 👍
