### ISSUE TITLE
Duplicated module in grid

### ISSUE THREAD

**Issue by ellmetha** [djangopackages/djangopackages#336]
Hi ;)
My Django module ("django-machina") seems to be duplicated in the "Forums" grid: https://www.djangopackages.com/grids/g/forums/

It appears that I cannot rectify this by myself. Is it possible to fix this?

**Comment by pydanny** [comment]
I'm investigating it now. Sorry for the delay, been busy with family medical emergency.

**Comment by michaeljohnbarr** [comment]
I believe this has been remedied. I don't see it being duplicated any longer.

**Comment by jayfk** [comment]
Indeed. This should work again!
