### ISSUE TITLE
Add statuspage

### ISSUE THREAD

**Issue by pydanny** [djangopackages/djangopackages#348]
We should use @jayfk's work: https://github.com/jayfk/statuspage

**Comment by vaibhav-jain** [comment]
I have placed the request to enable status page using the repo mentioned above they also have an option to do it using https://corestatus.io

![image](https://user-images.githubusercontent.com/4224414/78188458-e0dcd100-748d-11ea-8233-4a3a3b6c971e.png)

**Comment by ryancheley** [comment]
@jefftriplett this seems like an interesting idea, but not sure if it may be better to look at implementing [health-check](https://pypi.org/project/health-check/)
