### ISSUE TITLE
New category: monitoring

### ISSUE THREAD

**Issue by morenoh149** [djangopackages/djangopackages#416]
I was looking for a good monitoring solution.

Came across
* https://github.com/mwarkentin/django-watchman
* https://github.com/KristianOellegaard/django-health-check
* https://github.com/mvantellingen/django-healthchecks

**Comment by aleksihakli** [comment]
Hi,

Monitoring is already a grid on the site:

https://djangopackages.org/grids/g/monitoring/

**Comment by morenoh149** [comment]
how is it discoverable? I don't see it in the menu 
![screen shot 2017-01-31 at 2 19 38 pm](https://cloud.githubusercontent.com/assets/587438/22480730/61456572-e7c0-11e6-85ac-1c43509ed601.png)

**Comment by aleksihakli** [comment]
The grid is not visible in the top bar, those grids are only editable by moderators. It can be found by searching for the right grid, however:

![image](https://cloud.githubusercontent.com/assets/2477934/22506548/b83e7930-e889-11e6-9a71-f54ce2f9f15c.png)

**Comment by jefftriplett** [comment]
👋  newer maintainer here, Monitoring seems like a good addition to the heading/featured grids so I added that and then verified and added a few of the packages you mentioned. 

Thanks again for the suggestions!
