### ISSUE TITLE
Add manual verification of Python 3 compatibility

### ISSUE THREAD

**Issue by lorenz-bienek** [djangopackages/djangopackages#450]
When browsing through the packages I tend to ignore all packages where it shows the missing compatibility with Python 3. But there a quite a number of packages that are compatible.  What leads to this incorrect classification is the fact that authors don't add the Python versions to the package metainformation. A (random) example would be [https://djangopackages.org/packages/p/django-request/](https://djangopackages.org/packages/p/django-request/).

I suggest to add the possibility to let users verify compatibility for those cases. To make clear that there could be errors a third state for those manual user verifications would make sense.

**Comment by patrys** [comment]
We have a project (Saleor) that is not only compatible with Python 3 but is about to drop Python 2 compatibility yet Packages shows it with a red cross.

**Comment by jayfk** [comment]
These problems tend to get fixed as Python 3 is used in more and more projects. If you find a package that is listed as incompatible with Python 3, tell the package maintainers about it or even better submit a pull request to update the projects setup.py.

**Comment by patrys** [comment]
@jayfk I am the maintainer of [Saleor](https://djangopackages.org/packages/p/saleor/). Saleor is Python 3 only. There's no way for me to indicate that on Django Packages. The project is not pip-installable so it does not have a `setup.py`.
