### ISSUE TITLE
Deprecate/remove unwanted views and features

### ISSUE THREAD

**Issue by jayfk** [djangopackages/djangopackages#459]
The idea is to make djangopackages.org smaller and easier to maintain. 

Some views are no longer useful and pull in a lot of problematic dependencies. One example is the profiles view at https://djangopackages.org/profiles/:

- It's not really useful
- It pulls in problematic dependencies

**Comment by pydanny** [comment]
Individual profiles will remain, I presume? I'm asking because people use them as part of their CV.

**Comment by jayfk** [comment]
> Individual profiles will remain, I presume? I'm asking because people use them as part of their CV.

Absolutely!

**Comment by hebertjulio** [comment]
We would have a URL like this?
https://djangopackages.org/profiles/<USERNAME>

And whats information would appear on this page?
