### ISSUE TITLE
Add rate limiting

### ISSUE THREAD

**Issue by jayfk** [djangopackages/djangopackages#471]
Some API endpoints are getting hammered, saturating the uwsgi worker pool from time to time. 

Add a rate limit of 1-2 requests/s.

**Comment by pydanny** [comment]
Rate limiting is a good thing. We can add a pay option for people who want to hit the data more frequently.

**Comment by jayfk** [comment]
I've added a rate limit of 2 requests/s with a burst of 3 requests/s in https://github.com/djangopackages/djangopackages/commit/7ebad7a62245b246997003e07f035b18a0b1013b.


> Rate limiting is a good thing. We can add a pay option for people who want to hit the data more frequently.

Yup. Let's see how many are bitten by this :)
