### ISSUE TITLE
BSD License erroneously identified as Custom

### ISSUE THREAD

**Issue by jambonrose** [djangopackages/djangopackages#483]
Expected Behavior: my BSD-licensed project should be listed as being BSD licensed on the project page of djangopackages.org.

Actual Behavior: my BSD-licensed project is listed as being under a custom license.

[The package in question.](https://djangopackages.org/packages/p/django-improved-user/)

The license is properly listed [on PyPI](https://pypi.python.org/pypi/django-improved-user), and matches the license in [`settings/base.py`](https://github.com/djangopackages/djangopackages/blob/51793758c51a935a47a689d6a50603d5f9caecb7/settings/base.py#L358) (set in [`setup.py`](https://github.com/jambonsw/django-improved-user/blob/357b7de1186e054ec7cc588e29708e2ebcfdcc4c/setup.py#L176) of [django-improved-user](https://github.com/jambonsw/django-improved-user)).

**Comment by jambonrose** [comment]
By the looks of it, [djangopackages prefers to use the license field over the classifiers](https://github.com/djangopackages/djangopackages/blob/51793758c51a935a47a689d6a50603d5f9caecb7/package/models.py#L178).

If I am reading this correctly, I've specified 'Simplified BSD License' as the license field, whereas djangopackages is expecting a simple 'BSD License'  string.

For the moment, I will switch django-improved-user to use the simpler string. However, in doing so, I am removing relevant information for developers (Simplified vs Revised, or 2-clause vs 3-clause). Not essential information, but relevant nonetheless.

Would the maintainers of this package be interested in a pull-request that prioritizes the license classifiers over the license field? I would argue that classifiers can be matched more easily than strings set by developers.

**Comment by jambonrose** [comment]
PS - If you are not interested in a PR to change this behavior, please close this issue.

**Comment by jayfk** [comment]
There's also a normalize license function here: https://github.com/djangopackages/djangopackages/blob/d8d3ca201cebf47a08e07daffc1ded6d71e4b175/package/utils.py#L58-L73

If you care enough, it'd awesome to do some fuzzy matching against the SPDX license database. There's a ruby gem available but I wasn't able to find anything for python: https://github.com/librariesio/spdx

**Comment by jefftriplett** [comment]
Thank you for the info and overview on this. This appears to be working since the 0.5.2 release. 

I suspect at least the license types needs to be reviewed.
