### ISSUE TITLE
"429 Too many requests" error on custom instance of djangopackages software deployed via fabfile and settings/docker.py 

### ISSUE THREAD

**Issue by noisy** [djangopackages/djangopackages#485]
currently I am working [on a forked repository](https://github.com/noisy/steemprojects.com) on https://alpha.steemprojects.com/ 

Service is not officially lunched yet, so traffic is minimal... but sometimes when only I am using a website, I am reciving 429 error. I am not a deployment or server expert... so I am wondering, whether my configuration is ready for production.

I am deploying my service with:

`fab production deploy`

I am wondering whether this is fault of uwsgi or should I switched to gunicorn or something. Do you have any suggestions?

**Comment by jayfk** [comment]
The service is rate limited with 2 requests per second (3 burst): https://github.com/djangopackages/djangopackages/blob/master/compose/caddy/Caddyfile#L16
