### ISSUE TITLE
Question: Remove app from grid

### ISSUE THREAD

**Issue by funkyfuture** [djangopackages/djangopackages#486]
i see a redundant packgage in [this grid](https://djangopackages.org/grids/g/feedback/). is there a way to remove one? i'm logged in on the site, but can't spot any such functionality.

*addendum:* also [here](https://djangopackages.org/grids/g/forms/)

**Comment by pydanny** [comment]
@funkyfuture, what's the duplicate in the form grid?

**Comment by funkyfuture** [comment]
one that i can spot atm is `DJANGO MULTIPLE FIELD CLEAN`.

**Comment by vaibhav-jain** [comment]
> one that i can spot atm is `DJANGO MULTIPLE FIELD CLEAN`.

Hi @funkyfuture,

I can't seem to find the duplicate closing this for now. Please re-open if needed
