### ISSUE TITLE
How to delete the feature from the grid?

### ISSUE THREAD

**Issue by yn-coder** [djangopackages/djangopackages#490]
How to delete the feature from the grid?

For example - https://djangopackages.org/grids/g/file-managers/, `Integrates with tinymce` is types (by someone) 3 times.

How to delete it?

**Comment by pydanny** [comment]
To delete it, you request the change here. 

Please check that the site is working as expected!

**Comment by vaibhav-jain** [comment]
Closing this for now as the site is working as expected. @yn-coder please re-open if needed
