### ISSUE TITLE
Report irrelevant packages; report irrelevant grid additions 

### ISSUE THREAD

**Issue by barseghyanartur** [djangopackages/djangopackages#501]
How to report (ask for removal of) irrelevant packages? The one mentioned below is PHP work-on-progress something, totally irrelevant:

- https://djangopackages.org/packages/p/grandverse-php/

How to report (ask for removal of) irrelevant grid additions? For instance listing of `TastyPie` in CMS grid:

- https://djangopackages.org/grids/g/cms/

**Comment by barseghyanartur** [comment]
No comments at all?

I regularly see irrelevant additions, such as this:

- https://djangopackages.org/packages/p/mydjango/

**Comment by barseghyanartur** [comment]
https://github.com/Phong97/mysite

**Comment by pydanny** [comment]
Thanks @barseghyanartur for the reports. Those packages have been removed.

**Comment by barseghyanartur** [comment]
It seems that we need a more effective solution.

- https://djangopackages.org/packages/p/mydjango/

**Comment by jayfk** [comment]
Feel free to open a PR with your solution :)
