### ISSUE TITLE
Dangerously dead package.

### ISSUE THREAD

**Issue by shayneoAtNorwood** [djangopackages/djangopackages#506]
This package, is still listed high for django user profile apps.

https://djangopackages.org/packages/p/django-userena/

However the last commit was 2 years ago, and one year ago someone reported a major vunerability

https://github.com/bread-and-pepper/django-userena/issues/548

Its still there. This is one of those shut-down-server-and-do-full-audit level show stoppers.

I think leaving the app there endangers django projects by coders who arent in the habit of ticket list deep dives.

Thanks,
Shayne.

**Comment by pydanny** [comment]
Many, MANY thanks for letting us know.

I updated the django-userena entry to point at an actively maintained fork: https://djangopackages.org/packages/p/django-userena/
