### ISSUE TITLE
Python 3 support seems to depend on PyPI presence

### ISSUE THREAD

**Issue by patrys** [djangopackages/djangopackages#507]
I am the maintainer of [Saleor](https://djangopackages.org/packages/p/saleor/). Saleor is Python 3 only. There's no way for me to indicate that on Django Packages. The project is not pip-installable so it does not have a `setup.py`.

**Comment by NyanKiyoshi** [comment]
Bump.

**Comment by vaibhav-jain** [comment]
@patrys just checking is it still an issue?

**Comment by patrys** [comment]
Yes, it's still an issue. If you look at the [e-commerce grid](https://djangopackages.org/grids/g/ecommerce/) you will see that Saleor is listed as not supporting Python 3 despite the fact that the project itself only supports Python 3.7+.

**Comment by NyanKiyoshi** [comment]
We are still unable to specify classifier information without PyPi presence

**Comment by jefftriplett** [comment]
Closing this issue because the metadata now exists on PyPI. The better fix is a pretty massive cleanup of our existing data and then changing some assumptions around that Packages should be assumed Python 3 by default. Then we can change how scoring works with Python 2 only packages.
