### ISSUE TITLE
"Fetch latest data" error

### ISSUE THREAD

**Issue by grantjenks** [djangopackages/djangopackages#509]
1. I was here: https://djangopackages.org/packages/p/modelqueue/
2. I clicked "Fetch latest data"
3. An error occurred at https://djangopackages.org/packages/modelqueue/post-data/ saying: "Error
If this seems like a bug, would you please do us a favor and create a ticket?"
4. I made this ticket.

Thanks for djangopackages.org Love it!

**Comment by joshua-s** [comment]
It seems that Django Packages is broken since the launch of pypi.org: #508
