### ISSUE TITLE
Forums section disappeared

### ISSUE THREAD

**Issue by marqpdx** [djangopackages/djangopackages#514]
HI,

was linked to https://djangopackages.org/grids/g/forums/

and it returned 404, and said to post issue.

thx,
m

**Comment by marqpdx** [comment]
maybe it’s worth renaming as “Discussion Forums”; might reduce the confusion a tad.

thanks for restoring!
:)
m

**Comment by rafalp** [comment]
I don't think that renaming "Forums" to "Discussion Forums" would prevent people that obviously just follow "forums" keyword and then find first text area on the page that they can use to leave message.
