### ISSUE TITLE
Typo in grid description

### ISSUE THREAD

**Issue by guettli** [djangopackages/djangopackages#519]
This grid https://djangopackages.org/grids/g/authorization/

contains the words "Authorization backends".

AFAIK this does not exist. There are "Authentication backends".

I personally think, that the term "Authorization" should be avoided and the term "Permission" should be used. The two auth-terms sound so very similar, that it is better to use a different term.

**Comment by guettli** [comment]
Related: https://github.com/guettli/programming-guidelines/blob/master/README.rst#make-a-clear-distinction-between-authentication-and-permission-checks

**Comment by guettli** [comment]
Anybody out there?

**Comment by vaibhav-jain** [comment]
HI @guettli 

we already have https://djangopackages.org/grids/g/perms/

this has been fixed AFAIK this does not exist. There are "Authentication backends".

reopen if needed
