### ISSUE TITLE
Couldn't find env file

### ISSUE THREAD

**Issue by natea** [djangopackages/djangopackages#532]
When I follow the instructions and run the first command, it tells me that it can't find the `.env.local` file.

```
$ docker-compose -f dev.yml build
ERROR: Couldn't find env file: /Users/nateaune/Documents/code/djangopackages/.env.local
```
It looks like this file gets copied in the next step. Should these two commands be swapped in order?

**Comment by vaibhav-jain** [comment]
HI @natea 

Please have a look https://github.com/djangopackages/djangopackages#quickstart  I think this is in order. Closing now
