### ISSUE TITLE
Delete package

### ISSUE THREAD

**Issue by OmenApps** [djangopackages/djangopackages#535]
Someone added 'network' as a package at https://djangopackages.org/packages/p/cyrano31/

The repo link just points to github.com, and I couldn't find any information for any package by searching google and pypi for a combination of 'network' and 'cyrano31'

**Comment by rexhepberlajolli** [comment]
The link you mentioned returns a 404, I assume this issue has been resolved but if not feel free to reopen issue

**Comment by agusmakmun** [comment]
hello @rexhepberlajolli , I have the similar issue:

https://djangopackages.org/packages/p/draceditor/
https://djangopackages.org/packages/p/draceditor/

has replaced with:

https://djangopackages.org/packages/p/martor/
https://github.com/agusmakmun/django-markdown-editor

can you please remove this package: https://djangopackages.org/packages/p/draceditor/
