### ISSUE TITLE
Auto-complete packages comparison

### ISSUE THREAD

**Issue by mangelozzi** [djangopackages/djangopackages#542]
I hope this is the right place, but having searched https://djangopackages.org/faq/ all over this is the only place I could find to submit a correction.
In the comparison of auto-complete packages:
https://djangopackages.org/grids/g/auto-complete/
It says Django-autocomplete-light supports "**CharField completion**", my research is showing that it used to, but not in Python3. I think it would be great to correct the documentation to save others from being misguided. Something like a tick and a cross, and say only Python2 etc.

**Comment by vaibhav-jain** [comment]
Hi @michael-angelozzi 

I can do that but I'm not sure what is needed to be corrected here, It is intended to be just for hinting the users about the feature only.

**Comment by vaibhav-jain** [comment]
closing this due to no response from the original author @mangelozzi
