### ISSUE TITLE
Installation fails due to conflicting certifi version

### ISSUE THREAD

**Issue by NeolithEra** [djangopackages/djangopackages#545]
Hi, users are unable to run djangopackages due to dependency conflict with _**certifi**_ package. As shown in the following full dependency graph of **_djangopackages_**, **_djangopackages_** requires _**certifi==2016.2.28**_，while **_requests==2.22.0_** requires _**certifi>=2017.4.17**_.

According to pip’s “first found wins” installation strategy, _**certifi==2016.2.28**_ is the actually installed version. However, _**certifi==2016.2.28**_ does not satisfy _**certifi>=2017.4.17**_.

### Dependency tree------
```
djangopackages-master
| +-certifi(version range:==2016.2.28)
| +-chardet(version range:==2.3.0)
| +-coverage(version range:==4.3.4)
| +-dj-pagination(version range:==2.2.1)
| +-django(version range:==1.11.11)
| | +-pytz(version range:*)
| +-django-anymail(version range:==2.0)
| | +-django(version range:>=1.8)
| | | +-pytz(version range:*)
| | +-requests(version range:>=2.4.3)
| | | +-certifi(version range:>=2017.4.17)
| | | +-chardet(version range:<3.1.0,>=3.0.2)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:<1.26,>=1.21.1)
| | +-six(version range:*)
| +-django-braces(version range:==1.9.0)
| +-django-crispy-forms(version range:==1.6.1)
| +-django-debug-toolbar(version range:==1.5)
| | +-django(version range:>=1.8)
| | | +-pytz(version range:*)
| | +-sqlparse(version range:>=0.2.0)
| +-django-environ(version range:==0.4.0)
| | +-django(version range:*)
| | | +-pytz(version range:*)
| | +-six(version range:*)
| +-django-extensions(version range:==1.6.7)
| | +-six(version range:>=1.2)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be **_certifi>=2017.4.17_**. 
I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency certifi, and use the certifi transitively introduced by requests.


Which solution do you prefer, 1 or 2?
@pydanny Please let me know your choice. I can submit a PR to solve this issue.

**Comment by rexhepberlajolli** [comment]
This has been solved by https://github.com/djangopackages/djangopackages/commit/9aa70fb51cf0540cd5cb94b61932d36a02fc4211
