### ISSUE TITLE
Error (At least the index page says it is)

### ISSUE THREAD

**Issue by isik-kaplan** [djangopackages/djangopackages#547]
I normally wouldn't create an issue for this as it seems it is just down with no useful information on the client side but the wish was so polite that I had to create an issue. So this is just basically a heads up that the website is down, at least that's what I figured.

![image](https://user-images.githubusercontent.com/36948560/64481711-e077a280-d1ea-11e9-9d25-e4e853a8e286.png)

Edit: It seems like it is only the index, as I can access rest of the website if I just directly type in the url.
Edit2: Login button fails with the same page.

**Comment by jayfk** [comment]
Fixed, see https://github.com/djangopackages/djangopackages/issues/548
Thanks for bringing this up
