### ISSUE TITLE
Homepage doesn't work

### ISSUE THREAD

**Issue by jrlv16** [djangopackages/djangopackages#548]
I look for django packages on google and tried to open the django packages homepage I got a message asking me to submit an issue

**Comment by isik-kaplan** [comment]
#547 I thought they would've fixed it by now as I think this is a very popular website.

**Comment by amitjindal** [comment]
Still there.

**Comment by Pandorin** [comment]
Sad...

**Comment by jayfk** [comment]
I'm on git guys

**Comment by jayfk** [comment]
fixed, thanks for everyone commenting here! We really need to update our monitoring infrastructure. We used opbeat in the past. They shut down but are still referenced in the code.

If someone has the time to take a look at it, pull requests are welcome :)
