### ISSUE TITLE
delete duplicate package

### ISSUE THREAD

**Issue by sheppard** [djangopackages/djangopackages#555]
Hi, I renamed a project on GitHub and created a new entry on djangopackages before realizing I could just rename the existing entry.  So, now there are two entries for the same project.  Since the rename worked well, I think it makes sense to keep the older one and delete the new one.

Keep: https://djangopackages.org/packages/p/itertable/
Delete: https://djangopackages.org/packages/p/itertable-delete/

**Comment by rexhepberlajolli** [comment]
itertable-delete got removed, thanks for reporting this
