### ISSUE TITLE
Proposal for django-migrate-sql-deux

### ISSUE THREAD

**Issue by petrprikryl** [djangopackages/djangopackages#575]
Would be possible to add https://github.com/festicket/django-migrate-sql into database migration section https://djangopackages.org/grids/g/database-migration/?

I found it accidentally and it resolves my headache problem elegantly. I think that many people have same issue while installing raw sql migrations.

**Comment by vaibhav-jain** [comment]
Hi @petrprikryl 

Added https://djangopackages.org/packages/p/django-migrate-sql/

You can also add it yourself by singing
