### ISSUE TITLE
List Grids on Package Page for Discoverability

### ISSUE THREAD

**Issue by jplehmann** [djangopackages/djangopackages#579]
It would really help users discover related grids and packages, if the package pages themselves showed what grids a package was already assigned to.  This is a very easy feature.

(As an aside, I'd call them Tags not Grids, this was confusing to me for a few minutes.  But I assume that ship has long sailed.)

I love Django packages - thanks

**Comment by vaibhav-jain** [comment]
Hi @jplehmann 

This is already happening AFAIK 

https://djangopackages.org/packages/p/django-antispam/

<img width="536" alt="Screenshot 2020-06-09 at 4 44 18 PM" src="https://user-images.githubusercontent.com/4224414/84141282-915be800-aa70-11ea-8e21-668f075065bd.png">

reopen if neeed
