### ISSUE TITLE
Site is down [Error 500]

### ISSUE THREAD

**Issue by DmytroLitvinov** [djangopackages/djangopackages#582]
Hi there,

Seems like site returns 500 error.
![Selection_184](https://user-images.githubusercontent.com/16066485/81270731-d8128880-9053-11ea-8c4f-d4e60e8e37ae.png)

**Comment by x-N0** [comment]
Same here...

**Comment by pydanny** [comment]
Sorry, having to deal with paying work first.

**Comment by vaibhav-jain** [comment]
closing this now as the site is up and running
