### ISSUE TITLE
Typo in nav for "Anti Spam"

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [djangopackages/djangopackages#587]
As per screenshot, the nav of the package types says "anti sram" rather than "anti spam" (correct in url and everywhere else)

![Screenshot from 2020-06-03 08-31-46](https://user-images.githubusercontent.com/1381563/83608366-bafaa800-a574-11ea-9e15-711aad337bf3.png)

**Comment by vaibhav-jain** [comment]
Hi @samuele-mattiuzzo 

this has been fixed https://djangopackages.org/grids/g/anti-spam/
