### ISSUE TITLE
Upgrade to Django 3.2 LTS

### ISSUE THREAD

**Issue by luzfcb** [djangopackages/djangopackages#600]
The next LTS version of Django is relatively close.

Currently `djangopackages` runs on Django 2.2. 

The official mainstream support for Django 2.2 ended on December 2, 2019. 

Django 3.2 LTS is planned to be released in April 2021.

Starting upgrade attempts now may be a good idea.

Like any update process, it will be necessary to update and/or fix or replace some dependencies.
The direct dependencies of djangopackages are:

- [ ] certifi 
- [ ] chardet
- [ ] coverage
- [ ] Django
- [ ] django-braces
- [ ] django-crispy-forms
- [ ] django-debug-toolbar
- [ ] django-environ
- [ ] django-extensions
- [ ] django-floppyforms
- [ ] django-jsonview
- [ ] dj-pagination
- [ ] django-reversion
- [ ] django-secure
- [ ] webstack-django-sorting
- [ ] django-storages
- [ ] djangorestframework
- [ ] feedparser
- [ ] github3.py
- [ ] uwsgi
- [ ] httplib2
- [ ] logutils
- [ ] mimeparse
- [ ] oauth2
- [ ] psycopg2
- [ ] python-dateutil
- [ ] social-auth-core
- [ ] social-auth-app-django
- [ ] requests
- [ ] shortuuid
- [ ] six
- [ ] django-redis
- [ ] redis
- [ ] newrelic
- [ ] raven
- [ ] django-anymail

**Comment by vaibhav-jain** [comment]
HI @luzfcb 

Are you planning to work on this?

**Comment by luzfcb** [comment]
@vaibhav-jain My initial plan was to work on it in November, however my computer broke down and it took me almost 1 month to replace the defective part and my daughter was born and because of that I don't have a date for when I will have free time to go back to work on it,  so feel free to work on it.  That said, #602 is a blocker

**Comment by zerolab** [comment]
Django upgraded to 3.2 in #710 + various fixes in #713
