### ISSUE TITLE
Upgrade to Python 3.8 or higher

### ISSUE THREAD

**Issue by luzfcb** [djangopackages/djangopackages#601]
Currently, djangopackages runs on python3.6.
Staying in python3.6 can become a problem since Python 3.8 and 3.9 included a lot of new features, but they don't exist in python3.6, and that library maintainers will invariably start using them, making python3.6 an upgrade blocker for the python dependencies listed on #600 

The python3.6 official security support ends on December 2021.
The python3.8 is released on October 14, 2020, and the security support is planned to end on October 2024.
The Django 3.2 alpha version already supports Python3.9.

**Comment by jefftriplett** [comment]
I took a baby step and upgraded to Python 3.7: https://github.com/djangopackages/djangopackages/pull/621 

Once I get the deploy process reworked to auto-deploy, I'll try Python 3.8/3.9 (in theory, it should just work)
