### ISSUE TITLE
Upgrade Caddy server

### ISSUE THREAD

**Issue by luzfcb** [djangopackages/djangopackages#602]
**Describe the bug**
Currently, it is no longer possible to compile the docker image with Caddy 0.10.3.
From what I understand, the Caddy binaries < 1.0 have been removed the Caddy servers by the Caddy maintainers.
We should upgrade to Caddy 2 or replace Caddy with something else.

The error traceback:

```bash
luzfcb@fabio-pc:~/projects/opensource/djangopackages$ docker-compose build caddy
Building caddy
Step 1/12 : FROM alpine:3.5
 ---> f80194ae2e0c
Step 2/12 : LABEL maintainer "Abiola Ibrahim <-------@gmail.com>"
 ---> Using cache
 ---> 49dce7fc6452
Step 3/12 : LABEL caddy_version="0.10.3" architecture="amd64"
 ---> Using cache
 ---> 47e79721424f
Step 4/12 : ARG plugins=http.ratelimit
 ---> Using cache
 ---> 14bf4a28a192
Step 5/12 : RUN apk add --no-cache openssh-client git tar curl
 ---> Using cache
 ---> a746bc0c9285
Step 6/12 : RUN curl --silent --show-error --fail --location       --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o -       "https://caddyserver.com/download/linux/amd64?plugins=${plugins}&license=personal"     | tar --no-same-owner -C /usr/bin/ -xz caddy  && chmod 0755 /usr/bin/caddy  && /usr/bin/caddy -version
 ---> Running in a4270af940ea
curl: (22) The requested URL returned error: 404 Not Found
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Service 'caddy' failed to build: The command '/bin/sh -c curl --silent --show-error --fail --location       --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o -       "https://caddyserver.com/download/linux/amd64?plugins=${plugins}&license=personal"     | tar --no-same-owner -C /usr/bin/ -xz caddy  && chmod 0755 /usr/bin/caddy  && /usr/bin/caddy -version' returned a non-zero code: 2
```

**Comment by luzfcb** [comment]
Guide to upgrade Caddy of this project https://caddy.community/t/migrationg-caddyfile-from-0-10-version-to-2-2-version/10672

**Comment by luzfcb** [comment]
The Caddy server via https://github.com/lucaslorentz/caddy-docker-proxy works fine

**Comment by jefftriplett** [comment]
I will check this out. I'm using Caddy on another project (inspired by seeing this setup) and https://github.com/djangopackages/djangopackages/blob/master/.github/workflows/actions.yml#L71-L112 will at least build the docker image. 

I can switch to Traeffik too if that's easier.

**Comment by jefftriplett** [comment]
I upgraded this last night to v2.2 and then to v2.4.3 earlier today: 181a68aef21578a9b366958df79af5efbf5b8de1

On a deploy, the cert expired/errored out and complained that it couldn't be renewed after June 2021. So this is done now.
