### ISSUE TITLE
Sorting is strange

### ISSUE THREAD

**Issue by guettli** [djangopackages/djangopackages#612]
**Describe the bug**

The sorting is strange:

![image](https://user-images.githubusercontent.com/414336/115868831-528f1080-a43d-11eb-82e1-1ffbdde5fae5.png)

Why is the outdated package almost on top?

**To Reproduce**

1. Go to https://djangopackages.org/grids/g/payment-processing/
2. Look into the second column.
3. Look at the last release date: Several years old.

**Expected behavior**

I want to see maintained packages on top.

**Comment by JuanBenitezDev** [comment]
I guess it has something to do with the number of stars and forks that package has.
