### ISSUE TITLE
🔢  Add some type of SemVer/CalVer versioning scheme to the project

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#641]
It's easier to troubleshoot if we can track a version through from testing through production. 

My goto these days is CalVer, but I'm open to suggestions/changing this later.

**Comment by luzfcb** [comment]
I think CalVer is the right choice. Maybe `YYYY.MM.DD.01` (or `YYYY.MM.DD.001`) where `01` (or `001`) is today's deployment counter. 
I don't know if there is any library to manage the version that supports this.

**Comment by jefftriplett** [comment]
The last time I checked [bumpver](https://pypi.org/project/bumpver/), checked the feature boxed fairly well. 

`YYYY.MM.INC1` is kind of appealing because it's PEP440 compatible (even though this grid is wrong https://github.com/mbarkhau/bumpver#pattern-examples)

You can talk me into going with day, but seeing we deployed 35 times in August with a two "." pattern is appealing too.

**Comment by luzfcb** [comment]
`YYYY.MM.INC1` also works well
