### ISSUE TITLE
🔢 Link top 50 latest packages 

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#645]
Some useful Twitter feedback: 

> Unrelated, the list of 50 latest packages *exists*, but doesn't seem to be listed anywhere on the site. Do you know if there's any reason for this?
> I like to peruse this list occasionally to spot new and interesting packages, and I bet others would, too.
> https://djangopackages.org/packages/latest/

> https://twitter.com/JackDLinke/status/1423751706492428291

**Comment by gabrielolnunes** [comment]
Hi @jefftriplett, can we solve it by adding a **View more** link below the **Latest 5 Packages Added** section? If so, I'll give a try on it this week.

**Comment by jefftriplett** [comment]
@gabrielolnunes this sounds good to me. It might be worth looking at the other two sections too if things look off by adding just one. (Assuming we have paged for those too, or those could be follow up tasks.)

**Comment by jefftriplett** [comment]
Hi @gabrielolnunes, were you still wanting to take this on? If not, no biggie. I was holding off.

**Comment by ryancheley** [comment]
I'm going to take a stab at this
