### ISSUE TITLE
🤖  Automate Contributor Updates

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#687]
The goal is to automate noting contributors so that we don't overlook or miss anyone. 

Cookiecutter Django seems to solve this well: https://github.com/pydanny/cookiecutter-django/blob/master/.github/workflows/update-contributors.yml

**Comment by adellylima** [comment]
I agree with that, I'll work on it @jefftriplett

**Comment by jefftriplett** [comment]
Fixed in #717
