### ISSUE TITLE
🐘 Support dual licenses

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#690]
mentioned by @ShreehariVaasishta: Our current model stores a license as a varchar(100) string, but it's not uncommon to have dual-licensed projects. 

As a first step, we can create a `licenses` field which is an ArrayField of Char(100). 

Please leave the existing `license` and we will slowly migrate to it over a few upgrades. 

Please make this a nullable/blank-friendly field so that we can create a better migration path forward. 

https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#arrayfield

**Comment by ShreehariVaasishta** [comment]
Got it

**Comment by ShreehariVaasishta** [comment]
Hi, i will be taking up this issue and work on it.

**Comment by gabbyprecious** [comment]
Hello, I'm already on it

**Comment by jefftriplett** [comment]
Fixed in #722. This does a good job of taking care of the backend changes. I think there is a refactor of grids that we'll leverage later. 

Thanks again, @ShreehariVaasishta
