### ISSUE TITLE
:arrow_up: Migrate Read The Docs API from v1 to v3

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#691]
Thie check fails perma 302 errors from the RTD v1 API going away. There is a v3 API but this should really be checked once or periodically instead of every day. 

As far as I can tell, this just spams the RTD servers every day. 

https://github.com/djangopackages/djangopackages/blob/f86d3ed47b1d07d489fa5ebcb2d10b336c7c3d15/searchv2/builders.py#L62-L67

A better alternative might be to check the pypi json payload for the `["project_urls"]["Documentation"]` value and use that to store doc information *if the field is blank*. See

https://github.com/djangopackages/djangopackages/blob/main/package/models.py#L190-L210 

https://github.com/djangopackages/djangopackages/blob/main/package/models.py#L67

**Comment by dmoney** [comment]
Working on this.

**Comment by jefftriplett** [comment]
After thinking about this for a bit, I'm not sure what we need to hit RTD. I suspect checking `package.documentation_url` is filled in is good enough for what this is trying to do. 

I think it's worth periodically checking `package.documentation_url`, but once a day is a little much for re-indexing search.

**Comment by dmoney** [comment]
@jefftriplett Cool, that will mean a RTD API key won't have to be added to the settings, since their V3 API requires one.

**Comment by dmoney** [comment]
Is the search builder command just kicked off from a cron job?

**Comment by jefftriplett** [comment]
Yes, it runs via cron once a day.  There is some update/create lag between Grids and Packages as a result. It might be a good enhancement project to refactor this someday (to run hourly or per update, but hourly is probably good enough.)
