### ISSUE TITLE
⬆️  Upgrade to Django 3.x

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#707]
Let's do a quick pass to upgrade to Django 3.0 and fix anything that pops up. 

Once this is working, we'll move to Django 3.1 then Django 3.2.

**Comment by luzfcb** [comment]
@gabbyprecious Is it okay for you if I work on this?

**Comment by gabbyprecious** [comment]
@luzfcb  currently working on it, fixing issues after upgrade

**Comment by luzfcb** [comment]
@gabbyprecious Sure. Anyway, if you are blocked by some weird problem let me know if you want help.
