### ISSUE TITLE
Incorrect PyPI URLs on some packages

### ISSUE THREAD

**Issue by zerolab** [djangopackages/djangopackages#721]
**Describe the bug**
Some packages have a PyPI URL in the form of `http://pypi.python.org/pypi/https://pypi.org/project/...` for example:
https://djangopackages.org/packages/p/wagtail-grapple/
https://djangopackages.org/packages/p/wagtail-2fa/

**Additional context**
We use the API to pull in Wagtail packages and display on https://wagtail.io/packages/

Originally reported on https://github.com/wagtail/wagtail.io/issues/118

**Comment by jefftriplett** [comment]
@zerolab thank you for the report. This should be patched now both in #725 and in 06bf99a59ed325ab2dcf39fd39115b21949a92f1 

I suspect I'll have to do a cleanup script or something to fix these. I'll double-check tomorrow. We need to refactor more of the pypi logic to add some validation. 

It's also pretty neat to see Wagtails using this data. I have looked at it a few dozen times and I never realized it before :)

**Comment by jefftriplett** [comment]
I'm also noticing the pypi history isn't being fetched. More for tomorrow.

**Comment by zerolab** [comment]
Ah, thank you so much for the swift fix and response 🌟 ❤️

**Comment by jefftriplett** [comment]
I'm still seeing issues in a few categories, but I didn't have the headspace to poke around at the database. I will have a fix Friday or this weekend though with a better default for pypi too since I noticed we are hitting a redirect.
