### ISSUE TITLE
Hide PyPi side bar if info doesn't exist

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#729]
Some of our packages and frameworks won't have PyPI packages, so we should hide it in the sidebar. For example, check out the https://djangopackages.org/packages/p/saleor/ package 

Ideally, we'd check in the template if a `package.pypi_url` exists (see: https://github.com/djangopackages/djangopackages/blob/main/package/models.py#L65) and only show the sidebar text if it exists: 

https://github.com/djangopackages/djangopackages/blob/main/templates/package/package.html#L189-L190

**Comment by Atharva321** [comment]
Hii, I am interested to work on this issue.

**Comment by jefftriplett** [comment]
@Atharva321 sounds good 👍

**Comment by kishan3** [comment]
Hi @jefftriplett @Atharva321 I have already added a PR for this!

**Comment by Atharva321** [comment]
ok, gr8.
