### ISSUE TITLE
Invalid profile url in `ABSOLUTE_URL_OVERRIDES`

### ISSUE THREAD

**Issue by ShreehariVaasishta** [djangopackages/djangopackages#731]
When you click on `VIEW ON SITE`  in `http://<domain>/admin/auth/user/<pk>/change/`, it navigates to an invalid profile url i.e,  `http://<domain>/profiles/profile/<pk>/`. The correct url is `http://<domain>/profiles/<pk>/`.

**Comment by ShreehariVaasishta** [comment]
@jefftriplett  I'm assigning myself for this issues.

**Comment by jefftriplett** [comment]
@ShreehariVaasishta thank you!
