### ISSUE TITLE
Test suite fails; postgres version issue? 

### ISSUE THREAD

**Issue by smithdc1** [djangopackages/djangopackages#735]
Hi Jeff, thanks for everything you are doing here and the wider Django community 🙏

I'm very new to trying to run a project with docker so I'm probably running into the limits of my knowlege. Likely some of my terminology is a little loose, but hopefully it's close enough to make sense. The tl;dr here is that I'm strugling to run the test suite. I _think_ it's a postgres version issue (well, if I bump the postgres version the issues seem to go away). 

**Describe the bug**
I've setup the project with wsl2/vscode using the container in `.devcontainer`. When I try to run the tests with `pytest .` the majority of the tests fail. 

**To Reproduce**
1. Install the project using the provided container. 
2. Run `pytest .`
4. See most tests fail with an error like `django.db.utils.ProgrammingError: syntax error at or near "ON"`

**Expected behavior**
The tests pass. 

**Desktop (please complete the following information):**
 - Windows 11 / WSL2 / Ubuntu 20.04
 
**Potential Solution**
I see the project is running Django 3.2, the [release notes](https://docs.djangoproject.com/en/4.0/releases/3.2/#dropped-support-for-postgresql-9-5) shows that Django 3.2 supports Postgres 9.6 and higher. I tried changing the version in this [line](https://github.com/djangopackages/djangopackages/blob/895fa832458d3bd8d05bb3f36a43b5870078c71f/compose/postgres/Dockerfile#L1) (to 9.6) and once I had convinced docker to rebuild all of the containers I was able to see the tests pass. I'm not sure if this is the correct fix as it looks like you've [recently changed](https://github.com/djangopackages/djangopackages/commit/bde4890908ba66c36f2fa65b873f1dbb8703fd24) this to 9.4?

Thanks again for everything.

**Comment by jefftriplett** [comment]
Good catch. We did move from Postgres 9.4 to 13, but I wasn't 100% sure the best path forward for anyone with existing PRs open. WE are probably at a safe point where I can move us over. I'll do that then follow back up.

**Comment by jefftriplett** [comment]
This should now be fixed in #736. 

@smithdc1 thanks for the kind words. This project was built on the backs of giants over the years. 

I just booted up a fresh devcontainer under Postres 13 (the default now) and tests all run pass for me. Let me know if you see anything else or have questions I can help with. 🙏
