### ISSUE TITLE
CSS for the Grid filters are not being served.

### ISSUE THREAD

**Issue by gabrielolnunes** [djangopackages/djangopackages#740]
**Describe the bug**

Somehow the CSS for the Grid filters section implemented recently are not being properly served. Seem like a cache issue as CloudFlare is being used to minify its content. I may have missed something as well. It may be as simple as telling CF to invalidate the cache or something else I'm not aware.

**To Reproduce**

1. Go to some grid, like Authentication
2. Notice that the filters section checkboxes and labels have no space between them.

**Expected behavior**

The grid filters section implementation provides a new CSS for this fields which properly style them adding spaces and reducing font size for filters.

**Screenshots**

Wrong behavior:
![2021-10-06--10-43-23](https://user-images.githubusercontent.com/15188528/136214610-7fcbf519-8071-42dd-8326-3d88dcb407a1.png)

Expected behavior:
![2021-10-06--10-45-48](https://user-images.githubusercontent.com/15188528/136215073-20d6c0fc-3dbc-4d69-a142-1684737861c4.png)

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All
 

**Additional context**

This section was implemented recently in #719 which brings a new [CSS](https://github.com/djangopackages/djangopackages/blob/main/static/css/grid.css) for this section.
For some reason (maybe CF caching, or something else needed to CF invalidate the static files cache) an old version of `/static/css/grid.css` is being served.

**Comment by jefftriplett** [comment]
Fixed momentarily, but linking to #759 because that still needs to be addressed.
