### ISSUE TITLE
Change log links

### ISSUE THREAD

**Issue by smithdc1** [djangopackages/djangopackages#746]
The links in the changelog are a bit odd, they link to `api.github....` here's an example link. 

https://api.github.com/repos/djangopackages/djangopackages/pulls/743

I wonder if the template can just have the link number. Usually GitHub auto links when you use the format #(issue/pull number). 🤔

**Comment by r-lelis** [comment]
@smithdc1 I tested and github doesn't auto link the issue/PR with the #(issue/PR) format on a .md file :confused: . I had to put the link in there. Anyway, I opened the PR #758.
![2021-10-29_15-35](https://user-images.githubusercontent.com/87318486/139490921-d9e149ec-56ed-4294-b684-61a226edb791.png)

**Comment by jefftriplett** [comment]
Changes merged in #758. 

Thank you @smithdc1 for opening the ticket. Thank you @r-lelis for another pr to address it.
