### ISSUE TITLE
Incorrect `license` on package pages

### ISSUE THREAD

**Issue by smithdc1** [djangopackages/djangopackages#747]
**Describe the bug**
The `license` shown on package pages has started to show as `UNKNOWN` even where a licence was previously available. See [here](https://djangopackages.org/packages/p/django-axes/) and [here](https://djangopackages.org/packages/p/django_coverage_plugin/)

**To Reproduce**
1. Go to https://djangopackages.org/packages/p/django-axes/
2. Scroll down to Releases
3. See license in table is `UNKNOWN`

**Expected behavior**
Show the correct license

**Additional context**
I am sorry I've not had time to do a deep dive at this stage, but thought it best to log this now before I forget! However I noticed that there were recent commits in this area (e.g. https://github.com/djangopackages/djangopackages/commit/8bad61f4729818a923d903c40e8b49b75f854148 ) so suspect that is probably related.

**Comment by jefftriplett** [comment]
Marking this as resolved after watching it update for a few days. Thanks again for the report.
