### ISSUE TITLE
Invalidate Cloudflare cache when a static file changes

### ISSUE THREAD

**Issue by luzfcb** [djangopackages/djangopackages#759]
**Describe the bug**

On the #719 the [grid css](https://github.com/djangopackages/djangopackages/blob/930c7565ea216e42380694d32f1311b6d64e78b9/static/css/grid.css) was improved, but in production the old version is still served. 

I'm not sure if something is wrong with [`collectstatic`](https://github.com/djangopackages/djangopackages/blob/930c7565ea216e42380694d32f1311b6d64e78b9/compose/django/start.sh#L3), with some Caddy HTTP headers or a configuration on Cloudflare

**To Reproduce**
1. Open the https://djangopackages.org/static/css/grid.css and check if it contains the [new css ](https://github.com/djangopackages/djangopackages/blob/930c7565ea216e42380694d32f1311b6d64e78b9/static/css/grid.css)

**Expected behavior**

Whenever a new deployment occurs, if a static file has changed, Cloudflare must invalidate the previous version and serve the new version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Google Chrome v95.0.4638.54

**Comment by luzfcb** [comment]
I found out I don't have access to the Cloudflare account

**Comment by jefftriplett** [comment]
Should be doable with https://developers.cloudflare.com/cache/how-to/purge-cache

I transferred Cloudflare into my personal account, but I'll poke around to see if there's a team option or if we need to create a new account, etc.
