### ISSUE TITLE
Deleted version number keep appearing in the package page.

### ISSUE THREAD

**Issue by ip2location** [djangopackages/djangopackages#777]
**Describe the bug**
The deleted version 9.0.2 is still appear in the Releases table.

**To Reproduce**
1. Go to '[django-ip2location page](https://djangopackages.org/packages/p/django-ip2location/)'
2. Scroll down to 'Releases'
3. Compare the 'Releases' table to the [Release history in PyPI](https://pypi.org/project/IP2Location/#history).

**Expected behavior**
The deleted version 9.0.2 should disappear from the Releases table.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version 98.0.4758.82

**Additional context**
Are the content of the Releases table fetched from PyPI? If not, can you please tell us where is the data coming from? We would like to avoid the deleted version from continue appearing.

**Comment by jefftriplett** [comment]
Thank you for the report. I deleted it by hand. This is a limitation in the update trying to look at the last release. It looks like we have a license detection bug (it was dropped in the latest release) that I will look at too.
