### ISSUE TITLE
Emoji aren't being rendered in package.html

### ISSUE THREAD

**Issue by ryancheley** [djangopackages/djangopackages#806]
**Describe the bug**
When you go to a package with an emoji in it's repo description (for example https://djangopackages.org/packages/p/django-timeline-logger/) the emoji isn't being rendered properly. 

**To Reproduce**
1. Go to https://djangopackages.org/packages/p/django-timeline-logger/
2. Notice the repo description is
<img width="728" alt="Screen Shot 2022-03-14 at 8 27 20 PM" src="https://user-images.githubusercontent.com/9857779/158300270-5369e9ce-deec-465f-9038-8149a3f3a7df.png">

**Expected behavior**
1. Go to https://djangopackages.org/packages/p/django-timeline-logger/
2. The repo description should be "A reusable Django app to log actions and display them in a timeline :pencil:"

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser Safari
 - Version 15.3

**Additional context**
None

**Comment by jefftriplett** [comment]
If anyone cares to take this on and beat me to it, the [emoji](https://github.com/carpedm20/emoji) looks like a strong contender for a library worth using.

I would also eventually like to use [pypa/readme_renderer](https://github.com/pypa/readme_renderer)'s `readme_renderer.clean.clean()` method (or adapt it form bleach) to sanitize HTML and add "nofollow" links. I mention this package because it might be interesting to see what rendering READMEs looks like too.

**Comment by ryancheley** [comment]
@jefftriplett I'd love to give it a try!

**Comment by jefftriplett** [comment]
That would be wonderful. Feel free to work on one or both (two PRs is fine too) and reach out if you have any questions. I'm happy to make suggestions.

**Comment by ryancheley** [comment]
We may also want to apply this fix to the `title` field as well in the `package` model

**Comment by ryancheley** [comment]
I think the best approach here is going to be to add a template tag to [package_tags.py](https://github.com/djangopackages/djangopackages/blob/main/package/templatetags/package_tags.py) and then pass it [here](https://github.com/djangopackages/djangopackages/blob/a5d87000c8b83edf1d969301d12218bed7f72ebe/templates/package/package.html#L75)

Probably something like `emojify`

**Comment by jefftriplett** [comment]
Closing out in favor of #808 to continue the new scope of work.
