### ISSUE TITLE
Missing emoji template tag on base.html

### ISSUE THREAD

**Issue by ryancheley** [djangopackages/djangopackages#840]
**Describe the bug**
When searching for a package if the GitHub description returns an emoji, the emoji is returned as literal text instead of a rendering emoji. This was reported in issue #806 and fixed with PR #807 but it looks like I missed applying the template tag!

**To Reproduce**
1. Go to the [home page](https://djangopackages.org)
2. Enter 'Django Timeline Logger' in the search box
3. Scroll to the search results
4. See the description get returned as "A reusable Django app to log actions and display them in a timeline :pencil:"

**Expected behavior**
The results should return "A reusable Django app to log actions and display them in a timeline ✏️"

**Screenshots**
<img width="1154" alt="Screen Shot 2022-09-05 at 3 19 32 PM" src="https://user-images.githubusercontent.com/9857779/188517001-f5bd8cc1-5794-408d-8068-f959753ebfd5.png">

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
I'm more than happy to write up a PR. Just wanted to get the issue reported 😄

**Comment by ryancheley** [comment]
OK ... tried my hand at this tonight and discovered that the line that needs to be updated is [line 139](https://github.com/djangopackages/djangopackages/blob/main/templates/base.html#L139) which looks to be a JavaScript rendered element. When I added the `emojify` template tag the Chrome Dev Tools Console tab shows:
```
Error: Unknown provider: emojifyFilterProvider <- emojifyFilter
    at angular.min.js:29:439
    at Object.c [as get] (angular.min.js:27:142)
    at angular.min.js:30:21
    at Object.c [as get] (angular.min.js:27:142)
    at angular.min.js:109:235
    at u (angular.min.js:70:141)
    at w (angular.min.js:75:72)
    at l (angular.min.js:69:507)
    at Rc (angular.min.js:75:170)
    at angular.min.js:78:426
```

I have done a bit of googling, but so far no luck in finding anything on rendering an emoji with JavaScript.

**Comment by jefftriplett** [comment]
Interesting issue. The issue here is that the rendering is being processed by Angular which doesn't know what `emogify` is. 

A short-term fix would be to update the DRF serializer so that it reneders the contents before passing it off to Angular. Check out this serializer and we could filter the description field through the emojify filter - https://github.com/djangopackages/djangopackages/blob/0b528aeeecf588361611ac394163535975cb5cfc/apiv4/serializers.py#L128-L136 

A medium to long-term fix is I am debating switching search-driven views to htmx like on this page https://djangopackages.org/search/v3/ (header search isn't hooked up yet but the rest should work).

**Comment by jefftriplett** [comment]
I think https://github.com/djangopackages/djangopackages/commit/4f26c0cbe55176636a4ff8dbd6c61b7535eb67cb will cover the Search API.

**Comment by ryancheley** [comment]
> I think [4f26c0c](https://github.com/djangopackages/djangopackages/commit/4f26c0cbe55176636a4ff8dbd6c61b7535eb67cb) will cover the Search API.

Agreed! Looks like this is all fixed now 😄

**Comment by jefftriplett** [comment]
Thank you for the help in spotting it and narrowing it down. 🙏 

 If the htmx changes look approachable, there's lots of room there of help if that's something that looks appealing btw.

**Comment by ryancheley** [comment]
@jefftriplett would totally be up for working on implementing some htmx 😁. I’ve done it in a few (personal) projects so far and it’s just so nice to work with
