### ISSUE TITLE
Add support for emojificate

### ISSUE THREAD

**Issue by ryancheley** [djangopackages/djangopackages#848]
**Is your feature request related to a problem? Please describe.**
A [recent issue of Django News](https://django-news.com/issues/146) mentioned a project called `emojificate` which

>  improves web accessibility by turning text with emojis into text with accessible emojis

I believe adding this could help with packages that have emoji in their titles from an accessibility perspective

**Describe the solution you'd like**
Add support for emojificate to the templates that currently have the `emojify` template tag

**Describe alternatives you've considered**
None (other than not implementing it)

**Additional context**
To Be Added

**Comment by jefftriplett** [comment]
Fixed in #849
