### ISSUE TITLE
:books: Refactor/refresh/rewrite the contribution docs

### ISSUE THREAD

**Issue by ryancheley** [djangopackages/djangopackages#855]
**Is your feature request related to a problem? Please describe.**
I'd like to Refactor/refresh/rewrite contribution docs to make it easier for for people to walk through the initial setup and kick off process.

**Describe the solution you'd like**
Review the docs and update:

1. Update the `justfile` to include comments
2. Update the `faq.rst` to have a link to the contribution guide
3. Update the `contributing.rst` to include steps on using `just` and the `justfile`
4. Review the `readme.rst` for accuracy and update as needed

There may be other items discovered during the refactor phase. 

**Additional context**
This idea was based on [this conversation](https://twitter.com/webology/status/1583837021902028800?s=20&t=K6vQD38FEXwCaiBtBsRFzA) on Twitter

I'm more than happy to take this task on!

**Comment by ryancheley** [comment]
In reviewing the `justfile` there are a couple of commands that I'm still researching:

- caddy-fmt
- caddy-validate
- lint-fmt
- restore

The `caddy` options require `caddy` to be installed. I'm not sure if this is a production only thing or something else

The `lint-fmt` requires additional dependencies (`black`, `tryceratops`, `djhtml`) which one may want to install with `pipx`. Alternatively you could have a virtual environment set up locally, but in either case, the `readme.rst` doesn't have any reference to that (yet!)

The `restore` seem incomplete. The `docker-compose` commands are all commented out

**Comment by ryancheley** [comment]
@jefftriplett I'm reviewing the docs and have a few questions / am seeking input on. There are a few questions and it may be best to move this to a discussion instead of inline on the issue. If a discussion is a better spot for this, let me know and I'll create a discussion and move the questions there. 

# Questions

1. There are several links to ReadTheDocs, but the ReadTheDocs doesn't seem to match what's in the repo? Should we
   a. remove the references to the ReadTheDocs and drop that site?
   b. determine how to build the docs on ReadTheDocs and incorporate that into the publish process?
2. There are tips on the [Contributing page ](https://github.com/djangopackages/djangopackages/blob/main/docs/contributing.rst#tips) that seem like they may no longer apply with respect to the `starter` label and the `doc` label. I think the tips section should be removed
3. The docs reference the `develop` branch to be used for fetching upstream changes, but there isn't a develop branch. Should the docs be updated, or does a new branch need to be added

**Comment by jefftriplett** [comment]
I'd like to refresh the RTD docs (I started on it on my flight.) There is some dust to brush off there. 

I'd like to drop `docker-compose.dev.yml` and ship a default `docker-compose.yml` along with an opinionated `docker-compose.override.yml.example` file, which can be used to set custom ports and any other one-off things for local dev. There are a ton of small doc/readme changes for this. 

1. I think we can clean this up by updating our docs to be current
2. These seem fine for now and I can probably do a better job of using them or switch to whatever a more universal first-time-issue label would be since there are websites that help people find those
3. I'm cool with renaming `develop` to `main` since that's what we do.

**Comment by ryancheley** [comment]
In order to keep track of the changes I've made locally here is a list of the `rst` files that have been / will be reviewed

- [ ] introduction.rst
- [ ] license.rst
- [ ] install.rst
- [ ] index.rst
- [ ] troubleshooting.rst
- [ ] faq.rst
- [ ] opencomparison_settings.rst
- [ ] testing_instructions.rst
- [ ] management_commands.rst
- [ ] contributing.rst
- [ ] repo_handlers.rst
- [ ] apiv3_docs.rst
- [ ] lessons_learned.rst

**Comment by jefftriplett** [comment]
Adding https://myst-parser.readthedocs.io/en/latest/ to add another option for markdown should we want that as an option. 

I don't have a huge preference, but I think it's worth discussing if markdown is easier to update.

**Comment by jefftriplett** [comment]
Semi-not really related, but I saw this tweet from Hynek about moving to MyST. Sphinx has never fit my brain so I don't know if I should force myself through learning it better or punt and move to Markdown. Thoughts? 

https://twitter.com/hynek/status/1592865639739588608

**Comment by ryancheley** [comment]
I ran this command and confirmed that all of the `rst` files are in the `docs` directory (or a sub directory of `docs`):

```
find . -type f -name "*.rst"
```

The files are:

- [ ] install.rst
- [ ] index.rst
- [ ] testing_instructions.rst
- [ ] opinionated_install.rst
- [ ] contributing.rst
- [ ] management_commands.rst
- [ ] lessons_learned.rst
- [ ] apiv3_docs.rst
- [ ] license.rst
- [ ] troubleshooting.rst
- [ ] introduction.rst
- [ ] faq.rst
- [ ] repo_handlers.rst

In `deployment`:

- [ ] docker.rst
- [ ] index.rst



My general strategy is going to be to use pandoc to convert a single file (probably `licenserst`) to see how the results. If they check out, then applying the update more broadly.

**Comment by ryancheley** [comment]
OK, after a bit more playing this is what I've found:

1. Run this command to create `md` versions all of the `rst` (you'll need to have `rst-to-myst` installed)
```
rst2myst convert docs/**/*.rst
```
2. Update the `docs/conf.py`. see commit e3fe76e1
3. Run `make html --directory=docs` from the root.
