### ISSUE TITLE
:closed_lock_with_key: Auth Improvement

### ISSUE THREAD

**Issue by daheats** [djangopackages/djangopackages#903]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A better way to auth in order to use Django packages

**Describe alternatives you've considered**
N/A

**Additional context**
![Screen Shot 2023-02-02 at 1 45 41 PM](https://user-images.githubusercontent.com/20408533/216442020-f0d37ef2-b6fa-421a-af35-8ed4c9e59f2a.png)

**Comment by jefftriplett** [comment]
@daheats thanks. It's been a while since I logged out/back in. I'll look into what we need to match the names up with the org.

**Comment by saadmk11** [comment]
I think we need to transfer ownership of the OAuth App from personal account to the GitHub Organisation.
Ref: https://docs.github.com/en/apps/oauth-apps/maintaining-oauth-apps/transferring-ownership-of-an-oauth-app

**Comment by jefftriplett** [comment]
![Xnapper-2023-03-10-14 50 23](https://user-images.githubusercontent.com/50527/224425914-3d0b81ae-e8d7-458e-b7a9-a5ed9bf08519.png)

thank you @daheats 

I created a new org app and that way the keys are cycled too.
