### ISSUE TITLE
Incorrect formatting on grid page

### ISSUE THREAD

**Issue by boxed** [djangopackages/djangopackages#926]
https://djangopackages.org/grids/g/workers-queues-tasks/

The text looks like

```
Apps and services for running your Django apps in various parallel environments to the web server, freeing your project 
architecture from the HTTP-based service lifecycle:<br><br>* Construct daemons to batch-process large datasets<br>* 
Call functions on a recurring schedule<br>* Respond to system events<br>* Sync with external data sources without 
beach-balling <br><br>Use existing components (models, templates, &amp;c) and your favorite Django design patterns in
 these new contexts as you need -- while including Pythonic batteries from disciplines beyond web development.
```

I believe the correct way is to handle this is to delete whatever code tries to be smart by changing newlines to `<br>`, and instead use the `white-space: pre-wrap` CSS rule, which will work much better anyway (it can handle manual space and tab based indenting for example).

**Comment by jefftriplett** [comment]
This is mostly fixed. I thought we were using Markdown but the frontend templates weren't using it like I thought so I changed it up. We might revamp our markdown usage, but this works for now.
