### ISSUE TITLE
:whale: Add a `worker` service

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#961]
We loosely have celery support but have never switched over to it. The way cronjobs run today, they can take up the `django-a` process, so a nice stopgap until we support celery would be to add `worker` service and re-point our cronjobs to it for running our daily cron jobs. 

The worker service does not need to auto-run or restart. It should only be used for cronjobs without any external port mapping. 

```shell
12 23 * * * /usr/bin/docker compose -f /code/djangopackages/docker-compose.prod.yml run --rm django-a python manage.py searchv2_build
36 17 * * * /usr/bin/docker compose -f /code/djangopackages/docker-compose.prod.yml run --rm django-a python manage.py package_updater
48 21 * * * /usr/bin/docker compose -f /code/djangopackages/docker-compose.prod.yml run --rm django-a python manage.py pypi_updater
```

**Comment by jefftriplett** [comment]
I'm going to bump this up in priority because I think it might be bubbling up to impact the production service.

**Comment by saadmk11** [comment]
I have added a [PR](https://github.com/djangopackages/djangopackages/pull/1005) that should close this, but I think we could start a discussion about migrating to celery to run periodic tasks and some other tasks that can require significant amount of time such as `Fetch latest data` action.

**Comment by jefftriplett** [comment]
> I have added a [PR](https://github.com/djangopackages/djangopackages/pull/1005) that should close this, but I think we could start a discussion about migrating to celery to run periodic tasks and some other tasks that can require significant amount of time such as `Fetch latest data` action.

+1

Moving the "fetch latest data" action and some of the crontabs one or a few at a time would be an immediate improvement IMO. 

Have you used `django-q2`? I'm using it on a few high traffic websites and it hasn't missed a beat. I have used Celery for >15 years so I'm comfortable with it, but I found q2 easier to work with and it requires a lot fewer resources to run. I could go either way, but I was tempted to use it over celery since the migration path isn't terrible.

**Comment by saadmk11** [comment]
> > I have added a [PR](https://github.com/djangopackages/djangopackages/pull/1005) that should close this, but I think we could start a discussion about migrating to celery to run periodic tasks and some other tasks that can require significant amount of time such as `Fetch latest data` action.
> 
> +1
> 
> Moving the "fetch latest data" action and some of the crontabs one or a few at a time would be an immediate improvement IMO. 
> 
> Have you used `django-q2`? I'm using it on a few high traffic websites and it hasn't missed a beat. I have used Celery for >15 years so I'm comfortable with it, but I found q2 easier to work with and it requires a lot fewer resources to run. I could go either way, but I was tempted to use it over celery since the migration path isn't terrible. 

It is similar for me, I have been mostly using celery in production. But I have played around with django-q2 a bit some time ago and it could be interesting to try and migrate our tasks to django-q2. So, I am +1 with that. :)

**Comment by jefftriplett** [comment]
@saadmk11 Everything is merged and jobs and processing. Good job! 

There was an unrelated stale Caddyfile lock that wasn't getting reset on the `django-b` process. I'm not sure what that is about.

**Comment by jefftriplett** [comment]
This is looking good. I'll watch it tonight.
